### ISSUE TITLE
Allow deploy without any SageMaker Resources

### ISSUE THREAD

**Issue by QuinnGT** [aws-samples/aws-genai-llm-chatbot#108]
I noticed that if you deploy the solution with no SageMaker LLMs, Kendra as the only RAG, then amazon.titan-embed-text-v1 as the default embedding model, it still deploys a SageMaker Endpoint, config and model.

Pretty sure it's for the cross-encoder but I'm not using those features and it's added up to $160 just sitting there.

No pressure but would be nice to do the whole deployment without SageMaker costs in the mix.

**Comment by ldavis9000aws** [comment]
Agreed - did the same thing and it's like $20 bucks a day with the majority of the cost coming from that Sagemaker endpoint.  Got rid of the CDK deployment the other day just because of that.
