### ISSUE TITLE
Errors when following the readme

### ISSUE THREAD

**Issue by HugoCornu** [aws-samples/aws-genai-llm-chatbot#126]
I followed the readme 
using :

- cloud9
- bedrock in eu-central-1

when picking llama base or llama chat I got this error
`Template error: Unable to get mapping for LargeLanguageModelsLLamaV213BChatLlama2ChatPackageMapping3B2FA1E3::eu-central-1::arn`

when picking Kendra in the (Which datastores do you want to enable for RAG) question :
`Template format error: Unrecognized resource types: [AWS::Kendra::Index, AWS::Kendra::DataSource]`

when git pull
`Already up to date.`

**Comment by tobske** [comment]
Currently the project does not support eu-central-1 and if I execute `npm create` it does not provide me that option anyway. There is a part of the project that looks up the correct ARNs for a region and there are simply no ARNs for eu-central-1 yet.

**Comment by spugachev** [comment]
Llama 2 is not available in eu-central-1. Regions where Llama 2 is available:
ap-southeast-1
ap-southeast-2
eu-west-1
us-east-1
us-east-2
us-west-2

**Comment by HugoCornu** [comment]
Thanks
