### ISSUE TITLE
Feature request: Enable RAG on image understanding (Retrieval Augmented Image Captioning)

### ISSUE THREAD

**Issue by portisto** [aws-samples/aws-genai-llm-chatbot#145]
Hello, I deployed the new version by updating the CDK and redeploying. The Kendra RAG that I had in the previous version still works with the bedrock models however, when using custom SM model (idefics9b) I cannot select the RAG when doing prompt. Am i doing something wrong? Is there a config that needs to be changed so a RAG from a workspace can be used on a custom SM model endpoint? version used: 3.1.3

**Comment by portisto** [comment]
ok, in the config I see RagSupported=no (see image)
<img width="644" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/19312855/943ac740-8097-4ab5-80f4-7eef0aff29c9">

Anyway to change this?

**Comment by bigadsoleiman** [comment]
[IDEFICS](https://huggingface.co/blog/idefics) models purpose is to generate text grounded on uploaded images. 
Where do you see RAG fits here? 

If you want to test SM models with RAG you can deploy FalconLite, Lllama, Mistral, which are all text-to-text models

**Comment by portisto** [comment]
well, i would like to setup a multi-modal RAG enabled bot that can recognise image based on the input and create a prompt to query the RAG. Concretely, help me detect parts of the brain based on an MRI image with stimulated parts of the brain, then look up my knowledge base (in the RAG) to query documentation about that part of the brain. does that make sense?

**Comment by bigadsoleiman** [comment]
Understood, converting this to feature request so we can support this type of RAG on image understanding.
