### ISSUE TITLE
crawler for the Kendra index

### ISSUE THREAD

**Issue by portisto** [aws-samples/aws-genai-llm-chatbot#146]
I'm using a Kendra workspace with an index but when I want to add text, or crawl a website, the option is grayed out. How can I enable the crawler with my Kendra RAG? thx
v3.1.3

**Comment by kmanuwai** [comment]
The Kendra website crawler is currently not integrated with the solution. I am now working on doing this integration.

**Comment by portisto** [comment]
hello an thanks for the feedback. A workaround that I did was to use the index created when I created my first workspace, go to the AWS Console and add a new datasource, type Crawler. The Workspace in the solution needs to have the option to use "all data" and then it will combine both the files uploaded to the workspace and the crawler on the index in the responses.

**Comment by portisto** [comment]
> The Kendra website crawler is currently not integrated with the solution. I am now working on doing this integration.

maybe promote this to a new feature request?

**Comment by manuwaik** [comment]
Current work around:
1. In Kendra under the existing Index, create new data source - Web Crawler v2 (Do not sync yet)
2. In Kendra under the existing Index, select "Document Enrichments" then "Add Document Enrichment"
3. Fill out with details similar to the below image. Replacing the string value with your Workspace_Id
![image](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/11172727/055e1a9f-9612-4e24-b2c0-f793d9001fc7)
