### ISSUE TITLE
Feature: multi-LLM chat

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/aws-genai-llm-chatbot#147]
Allow for chatting with multiple LLMs at the same time. The functionality allow sending the same user query to multiple chat sessions, each with its own LLM configuration. 
Each session maintains its own message history, which can be later on retrieved in a single chat playground.
Allows for up to 4 simultaneous chat sessions using a single retriever.

This feature enables

**Comment by portisto** [comment]
+1
