### ISSUE TITLE
Feature request: ability to delete/erase domain data added to RAG workspace

### ISSUE THREAD

**Issue by saragerion** [aws-samples/aws-genai-llm-chatbot#149]
### Summary

It could be useful to be able to selectively delete specific domain data added in the RAG workspace.
Domain data I am referring to includes:
- Files uploaded 
- Text
- Q/A
- Websites

### Motivation
There are some use cases in which a company may want or need to delete specific domain data after it has been added to the RAG storage.  This can happen for example when companies need to adhere to compliance requirements and therefore should be able to erase private data from their workloads when requested.
Example: [European Union’s General Data Protection Regulation (GDPR)](https://aws.amazon.com/compliance/gdpr-center/) “right to erasure” or “right to be forgotten” requirements, when applicable.

**Comment by ajaylamba-provar** [comment]
Or the more common use case would be - the content has been updated.

**Comment by azaylamba** [comment]
@flamingquaks @massi-ang I'm trying to make changes for this, could you guys give some pointers to start with please?

**Comment by azaylamba** [comment]
I am working one this one. I have successfully implemented this for OpenSearch but my fork is no in sync with main after migration to AppSync. 
I will sync with main and will modify the code accordingly.

**Comment by azaylamba** [comment]
Update: Changes are done, testing in progress.

**Comment by azaylamba** [comment]
Finally, raised PR for this.

**Comment by azaylamba** [comment]
Changes for this have been merged to main, this issue can be closed as done.
