### ISSUE TITLE
Enhancement: add answer feeedback ratings

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/aws-genai-llm-chatbot#151]
While testing a new chatbot it is important to be able to gather information about the quality of the answers. Since quality might mean different things for different use cases, the "quality ratings" should be configurable per chatbot. 

This enhancement is about adding the possibility to define up to 5 rating criteria and the associated values. Rating criteria can then be associated with a chatbot and displayed in the UI at the bottom of each answer provided by the system. 
As the user changes the rating, they are stored in the chat history.

A chatbot administrator would then be able to get a report about all the answer rating and their associated metadata.

**Comment by azaylamba** [comment]
Changes are done and are out for review under https://github.com/aws-samples/aws-genai-llm-chatbot/pull/287

**Comment by azaylamba** [comment]
https://github.com/aws-samples/aws-genai-llm-chatbot/pull/287 has been merged, this issue can be closed.
