### ISSUE TITLE
Receiving error when using Playground

### ISSUE THREAD

**Issue by shotintoeternity** [aws-samples/aws-genai-llm-chatbot#156]
Thanks so much for your help building this amazing service! Unfortunately, I am receiving an issue when running the playground for the first time. When I attempt any queries, I am receiving the error below:

`<class 'ValueError'>:Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModelWithResponseStream operation: The requested operation is not recognized by the service.`

Does anyone have suggestions on troubleshooting steps I might be able to try? Thanks!

**Comment by magriggs** [comment]
I'm getting this as well

**Comment by bigadsoleiman** [comment]
Have you requested access to base models? Also note that titan models are still in preview so once you ensured you requested access to base models you might want to switch over to Claude, Cohere or AI21 ones.


For base model access check out https://github.com/aws-samples/aws-genai-llm-chatbot#amazon-bedrock-requirements

**Comment by shotintoeternity** [comment]
Hi, I have requested access to the base models, but none of the models I'm selecting are working properly. Do you have any additional thoughts on how to troubleshoot this issue? Thanks!

**Comment by shotintoeternity** [comment]
Here is a screenshot of my current base model access that verifies I have access to each of the model types.
<img width="479" alt="Model Access" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/266741/16b83623-475a-4ed8-8bce-0137059d1151">

**Comment by shotintoeternity** [comment]
I redeployed the CDK solution using the `bedrock-runtime` API endpoint during the `npm run create` portion of the setup, and this time the solution worked properly.
