### ISSUE TITLE
Can't run locally

### ISSUE THREAD

**Issue by skrinak** [aws-samples/aws-genai-llm-chatbot#159]
Looks like some amplify process is missing…

ConsoleLogger.js:122 [ERROR] 45:48.719 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.

**Comment by massi-ang** [comment]
Could you provide more detailed information on how to reproduce the error, since this project is not using Amplify.

**Comment by Wubbiez** [comment]
I have this same issue, it seems the aws-exports is not properly grabbing the environment variables. Are there any intermediate steps required to modify or refactor any files before running:
npm run build:dev
npm run dev

**Comment by massi-ang** [comment]
To run the frontend locally you just need to grab the `aws-exports.json` file from a deployed system.

After deploying the solution to your account, download the `aws-exports.json` file from `https://<xyz>.cloudfront.net/aws-exports.json` where `<xyz>` is your specific CloudFront distribution domain name. 

Copy the file into `./lib/user-interface/react-app/public` and then run `npm run dev` from the `./lib/user-interface/react-app` folder.

**Comment by zhu-xiaowei** [comment]
> To run the frontend locally you just need to grab the `aws-exports.json` file from a deployed system.
> 
> After deploying the solution to your account, download the `aws-exports.json` file from `https://<xyz>.cloudfront.net/aws-exports.json` where `<xyz>` is your specific CloudFront distribution domain name.
> 
> Copy the file into `./lib/user-interface/react-app/public` and then run `npm run dev` from the `./lib/user-interface/react-app` folder.

Thanks a lot, I have the same issue, It is recommended to add this step before running `npm run dev` in the readme.

**Comment by ajaylamba-provar** [comment]
> To run the frontend locally you just need to grab the `aws-exports.json` file from a deployed system.
> 
> After deploying the solution to your account, download the `aws-exports.json` file from `https://<xyz>.cloudfront.net/aws-exports.json` where `<xyz>` is your specific CloudFront distribution domain name.
> 
> Copy the file into `./lib/user-interface/react-app/public` and then run `npm run dev` from the `./lib/user-interface/react-app` folder.

This resolves the error and now able to run the app locally

**Comment by jtlz2** [comment]
Followed the instructions above, doesn't work for me!

**Comment by jtlz2** [comment]
OK there is a bug in the README - you have to make the `curl` call after the build step but before the run i.e.

```
npm run build:dev
curl https://<redacted>.cloudfront.net/aws-exports.json > ./lib/user-interface/react-app/public/aws-exports.json
npm run dev
```

Then you are good to go 👍

**Comment by massi-ang** [comment]
Hi, can you please explain what wasn't working by doing:
```
curl https://<redacted>.cloudfront.net/aws-exports.json > ./lib/user-interface/react-app/public/aws-exports.json
npm run build:dev
npm run dev
```
?

**Comment by jtlz2** [comment]
@massi-ang Sure - 

```
./lib/user-interface/react-app/public/aws-exports.json
```

was getting overwritten by `npm run build:dev`, which leads to @skrinak 's original amplify error/s.
