### ISSUE TITLE
Feature request: Conversation history

### ISSUE THREAD

**Issue by ajaylamba-provar** [aws-samples/aws-genai-llm-chatbot#173]
It would be good if the user conversation history is stored and the conversations can be continued later on. It would extend the usability of the chatbot to use in production.

**Comment by bigadsoleiman** [comment]
HI @ajaylamba-provar this is alreay supported. In Playground, you can click on the top right icon and you can manage/recover history.



<img width="291" alt="Screenshot 2023-11-02 at 11 27 55" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/83646217/7e03dd67-6c14-4d17-a003-309c272ae806">

**Comment by ajaylamba-provar** [comment]
Oh ok, sorry I missed it. I found it now. Thanks @bigadsoleiman.
I will close this ticket then.
