### ISSUE TITLE
Enhancement: Separation of workspaces between users

### ISSUE THREAD

**Issue by nagelpat** [aws-samples/aws-genai-llm-chatbot#181]
Currently, every authenticated user can see every workspace created by another user and send queries against it. This behavior can be a (data privacy) issue if different teams and users work on the same llm-chatbot deployment.

You can’t retrieve uploaded documents by another user directly but you can still retrieve information with a few queries against that workspace and the file name might even give some hints what the data is about.

A first step to implement workspace separation might simply be on the “UI” level and could be done with a feature flag for those who need it. Pretty sure that some users will ask to share workspaces with specific users (or teams) but that could be a later iteration. Thanks!

**Comment by abduljaleel** [comment]
Highly support this feature, in the enterprise environment data privacy concerns prevents using the chatbot because of public workspace behavior.

**Comment by hghandri** [comment]
Hi, 
this issue is already opened with same issue.

https://github.com/aws-samples/aws-genai-llm-chatbot/issues/227
