### ISSUE TITLE
Unable to install Opensearch RAG Engine

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#187]
If Opensearch is the only enabled RAG Engine in the config during deployment, then the whole deployment fails
It can only be installed together with Aurora and Kendra.
Has anyone hit it as well ?

**Comment by bigadsoleiman** [comment]
Hi @alexeyshishkin01

just pushed a fix that should address the OpenSearch deployment issues. 
You might want to re-clone and deploy from scratch.

**Comment by alexeyshishkin01** [comment]
thanks, let me check if it works after the fix

**Comment by alexeyshishkin01** [comment]
it looks like the issue is gone after applying the fix, pls. close the issue, thanks !
