### ISSUE TITLE
deployment problems with v 3.1.5

### ISSUE THREAD

**Issue by portisto** [aws-samples/aws-genai-llm-chatbot#205]
I just pulled the new version and i get the following issues while doing the build:

<img width="1302" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/19312855/77d67f24-92d1-43a7-b5d4-9e28380964fc">

After inspecting the repo I don't find this module. Is there something special that needs to be done while upgrading to the new version (i'm currently running v 3.1.3)?

**Comment by bigadsoleiman** [comment]
Hi @portisto 

this has been fixed in [this commit](https://github.com/aws-samples/aws-genai-llm-chatbot/commit/d3c8d4fed7978fc1f740aada7523e2d714024f66).
