### ISSUE TITLE
Error during 'Crawl website' due to Lambda timeout (900 sec)

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#209]
I hit the the subject for the following test:

- Test-Aurora-01
sentence-transformers/all-MiniLM-L6-v2 (384)
English
Negative inner product (<#>)
Create an index ON
Use hybrid search OFF
cross-encoder/ms-marco-MiniLM-L-12-v2
Chunk Size 1000
Chunk Overlap 200

Crawl Website
https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html
Follow Links ON
Page Limit 30

The error message is in the Step Function -> State Machine -> RagEnginesDataImportWebsiteCrawlingWorkflowWebsiteCrawlingXXX:
{
  "resourceType": "lambda",
  "resource": "invoke",
  "error": "Lambda.Unknown",
  "cause": "The cause could not be determined because Lambda did not return an error type. Returned payload: {\"errorMessage\":\"2023-11-09T11:13:49.868Z 3bc2ea69-11cc-4fa1-969e-897cc6070d84 Task timed out after 900.13 seconds\"}"
}

900 seconds is the max timeout for Lambda - https://docs.aws.amazon.com/lambda/latest/operatorguide/configurations.html#timeouts

Do you have plans to think about other architecture due to this Lambda limit ?
Otherwise the limit of 30 pages is not so big for real life scenarios

**Comment by QuinnGT** [comment]
I ran into the same issue on some sites, really just due to follow links. Sitemap has by far been the best but still a few large imports to deal with but I've done as much as 900 pages.

One small change I made is increasing the memory to 2GB so that it scales the CPU assigned to the function too.
![image](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/44334535/dca35cc1-d602-4c2d-b947-59e9ffdfe1b4)

**Comment by alexeyshishkin01** [comment]
It is strange that timeout happens while crawling https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html even for 30 pages
For some other sites I can successfully crawl 250 pages without any timeouts
Anyone can confirm it ?

**Comment by flamingquaks** [comment]
Crawling is done by the SageMaker inference endpoint, not the actual lambda. 
I've experienced this issue if I had too many other crawlers running. @alexeyshishkin01, were there other crawlers operations running at that time? Can you share the CloudWatch metrics for the SageMaker Inference Endpoint? I suspect that the endpoint is hitting a limit and isn't able to respond to requests in a timely manner.

**Comment by alexeyshishkin01** [comment]
I don't remember exactly if there were other crawlers running when I hit my Lambda timeout issue, but what was really strange is that there was a timeout for Amazon site and not timeout for other sites

**Comment by massi-ang** [comment]
@alexeyshishkin01 could you please provode the logs from the lambda function called `...RagEnginesDataImportWebsiteCrawl...`?

**Comment by alexeyshishkin01** [comment]
I don't have log files unfortunately any longer, but in my case it was easy to reproduce the issue - pls. see my above messages

**Comment by massi-ang** [comment]
I tested it and see that the processing Lambda stops at this link: https://docs.aws.amazon.com/pdfs/bedrock/latest/userguide/bedrock-ug.pdf#what-is-bedrock  
This page is a PDF and not a webpage and this cause the lambda to hang.  Fixing it.

**Comment by alexeyshishkin01** [comment]
My test was on the page https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html with the settings:
Follow Links ON
Page Limit 30
Do you also hit the issue here ?
The issue for this page was 100% reproduceable for me.

**Comment by massi-ang** [comment]
Yes, I crawled that page and got the issue I mentioned, as one of the links to follow is not a HTML page

**Comment by alexeyshishkin01** [comment]
Ok, thanks for clarification !

**Comment by alexeyshishkin01** [comment]
Nice !
