### ISSUE TITLE
Chatbot UI is stuck at "Loading models..."

### ISSUE THREAD

**Issue by uzaymacar** [aws-samples/aws-genai-llm-chatbot#21]
Screenshot attached below. Quickly inspecting [`Chat.tsx`](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/user-interface/react/src/components/chatbot/Chat.tsx), I get the impression that the `models` variable is never populated.

<img width="973" alt="Screen Shot 2023-08-20 at 1 16 04 AM" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/33473983/8c660af5-de9a-472b-91ad-071c1e18643e">

**EDIT**: I'm using a custom AWS SageMaker hosted model (Falcon) as I don't have access to AWS Bedrock yet.

**Comment by bigadsoleiman** [comment]
It gets populated [here](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/6dc6f3802ca5cf9ad19c5ed7e0c5c8f169e5de08/lib/user-interface/react/src/components/chatbot/Chat.tsx#L167).

Assuming the SageMaker Endpoint has been deployed successfully, can you double check that the `langchainInterface.addSageMakerEndpoint(...)` is called. Like [here](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/6dc6f3802ca5cf9ad19c5ed7e0c5c8f169e5de08/lib/aws-genai-llm-chatbot-stack.ts#L120)?

**Comment by bigadsoleiman** [comment]
After a dive deep might be related to #19 and the architecture used to build the common layer for model interface not matching the `RequestHandler` lambda function, which causes the `listModels` call to fail.

I've added [this](https://github.com/aws-samples/aws-genai-llm-chatbot/commit/3cbd90a23a9f5c5633e20333ce1d2afaf6a1c2de) to ensure the right `--platform` for Docker commands is passed where supported.

If you pull this and deploy it should build the common layer with the right target architecture. Docker might re-use your cached images so in case it doesn't, clean the docker cache.

**Comment by uzaymacar** [comment]
Thanks @bigadsoleiman I can confirm that the latest commits fix the issue -- I am able to play around with `amazon-Falconlite` now  🎉
