### ISSUE TITLE
RagEngines - SageMaker endpoint instance type

### ISSUE THREAD

**Issue by jyjohnson** [aws-samples/aws-genai-llm-chatbot#213]
1. Change the default to a cheaper instance type - e.g., ml.m5.large
2. Allow the user to select from several instance types via the `npm run create` wizard.
3. Alternatively, can SM Serverless endpoint be used ? 

https://github.com/aws-samples/aws-genai-llm-chatbot/blob/d3c8d4fed7978fc1f740aada7523e2d714024f66/lib/rag-engines/sagemaker-rag-models/index.ts#L37

**Comment by massi-ang** [comment]
Serverless endpoints and ml.m5 instances do not have GPUs. Since it seems you are looking at reducing cost, would it be ok if we had the possibility to start/stop the SM endpoint instance?

**Comment by jyjohnson** [comment]
Requires GPU so can't use a smaller instance
