### ISSUE TITLE
Add support for Bedrock Cohere embeddings

### ISSUE THREAD

**Issue by danielmitchell** [aws-samples/aws-genai-llm-chatbot#218]
Bedrock has recently added support for Cohere embeddings. It would be great if this app could support the English and multilingual Cohere embeddings models.

https://aws.amazon.com/blogs/aws/amazon-bedrock-now-provides-access-to-cohere-command-light-and-cohere-embed-english-and-multilingual-models/

**Comment by Gmreh** [comment]
Yes, that would be indeed an extremely beneficial update...
