### ISSUE TITLE
Using custom HuggingFace models

### ISSUE THREAD

**Issue by uzaymacar** [aws-samples/aws-genai-llm-chatbot#22]
Reading the details [here](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/sagemaker-model/README.md), it was my understanding that simply adding

```javascript
// LLaMa-2 example from HuggingFace (https://huggingface.co/upstage/Llama-2-70b-instruct-v2)
const llama_2_70B_instruct_v2 = new SageMakerModel(this, 'Llama-2-70b-instruct-v2', {
  vpc: vpc.vpc,
  region: this.region,
  model: {
    type: DeploymentType.Container,
    modelId: 'upstage/Llama-2-70b-instruct-v2',
    container: ContainerImages.HF_PYTORCH_LLM_TGI_INFERENCE_LATEST,
    instanceType: 'ml.g5.24xlarge',
    // https://github.com/awslabs/extending-the-context-length-of-open-source-llms/blob/main/custom-tgi-ecr/deploy.ipynb
    containerStartupHealthCheckTimeoutInSeconds: 600,
    env: {
      SM_NUM_GPUS: JSON.stringify(4),
      MAX_INPUT_LENGTH: JSON.stringify(12000),
      MAX_TOTAL_TOKENS: JSON.stringify(12001),
      HF_MODEL_QUANTIZE: 'gptq',
      TRUST_REMOTE_CODE: JSON.stringify(true),
      MAX_BATCH_PREFILL_TOKENS: JSON.stringify(12001),
      MAX_BATCH_TOTAL_TOKENS: JSON.stringify(12001),
      GPTQ_BITS: JSON.stringify(4),
      GPTQ_GROUPSIZE: JSON.stringify(128),
      DNTK_ALPHA_SCALER: JSON.stringify(0.25),
    },
  },
});
// Make model interface aware of the sagemaker endpoint and add the necessary permissions to the lambda function
langchainInterface.addSageMakerEndpoint({
  name: 'Llama-2-70b-instruct-v2',
  endpoint: llama_2_70B_instruct_v2.endpoint,
});
```

to [`aws-genai-llm-chatbot-stack.ts`](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/aws-genai-llm-chatbot-stack.ts) would be sufficient (similar to the `amazon/FalconLite` example).

However with this configuration I get the following error: `The following resource(s) failed to create: [Llama270binstructv2upstageLlama270binstructv2035C66C7]`. 

Any directions appreciated 🙏

**Comment by bigadsoleiman** [comment]
Hi @uzaymacar,

As of today, HuggingFace models require some research upfront before attempting a deployment.

Reason being, each model has its own unique requirements in terms of:
- `instanceType` (n. of GPU, Memory...)
- Environment Variables
- Prompting
- Request Parameters

This means you can't simply assume to re-use the same instance type and/or env vars for any other model.
The settings you used above are specifically made for FalconLite only.

### InstanceType and Env vars
For example, llama2-70B would require an `ml.g5.48xlarge` instance to start with (be careful with the costs) - check the table under `Deploy a model` section of this [blog post](https://aws.amazon.com/blogs/machine-learning/llama-2-foundation-models-from-meta-are-now-available-in-amazon-sagemaker-jumpstart/) for a map of Llama models / AWS instance type. 
And by the look of it no environment vars is needed.

These information as of today are bit sparse, some can be found in HuggingFace Model cards, community tab and/or some [blog posts](https://www.philschmid.de/sagemaker-falcon-llm) made for the purpose of deploying on SageMaker.

The `SageMakerModel` constructs simply saves you some heavy-lifting in terms of resources to write but the right settings like instanceType and env variable needs to be researched upfront and can't be assumed for HF models, sometimes you'll have to deal some trial and error too.

### Prompting and Request parameter
Lastly, in order for the application to communicate with the model correctly, you need to make sure you have the right  [model adapter](https://github.com/aws-samples/aws-genai-llm-chatbot/tree/main#model-adapters) [examples](https://github.com/aws-samples/aws-genai-llm-chatbot/tree/main/lib/model-interfaces/langchain/functions/request-handler/adapters) (we added one for llama already but for other models not listed [you need to write your own](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/model-interfaces/langchain/README.md). Usually the format of the prompt is explained in the HuggingFace model cards with examples.


I'll take sometime to collect this directions in one place, hope it clarifies.

**Comment by vikramshitole** [comment]
@uzaymacar was able to deploy Llama-2-13b-chat-hf, I guess the only thing missing in your code is the HUGGING_FACE_HUB_TOKEN

`     const llama2chat = new SageMakerModel(this, 'LLamaV2Chat', {
      vpc: vpc.vpc,
      region: this.region,
      model: {
        type: DeploymentType.Container,
        modelId: 'meta-llama/Llama-2-13b-chat-hf',
        container: ContainerImages.HF_PYTORCH_LLM_TGI_INFERENCE_LATEST,
        instanceType: 'ml.g5.12xlarge',        
        containerStartupHealthCheckTimeoutInSeconds: 600,
        env: {
              SM_NUM_GPUS: '4',
              HF_MODEL_ID: 'meta-llama/Llama-2-13b-chat-hf',
              MAX_INPUT_LENGTH: '2048',
              MAX_TOTAL_TOKENS: '4096',
              MAX_BATCH_TOTAL_TOKENS: '8192',
              HUGGING_FACE_HUB_TOKEN: process.env.HUGGING_FACE_HUB_TOKEN ? process.env.HUGGING_FACE_HUB_TOKEN : ''
        },
      },
    });

    
    // Make model interface aware of the sagemaker endpoint and add the necessary permissions to the lambda function
    langchainInterface.addSageMakerEndpoint({
      name: 'Llama-2-13b-chat-hf',
      endpoint: llama2chat.endpoint,
    });
  `
