### ISSUE TITLE
S3 as Data source

### ISSUE THREAD

**Issue by Gmreh** [aws-samples/aws-genai-llm-chatbot#228]
Hi guys, 
I suggest adding S3 bucket as an option as data origin.
regards

**Comment by alexeyshishkin01** [comment]
+1

**Comment by jstein-vr** [comment]
I believe Kendra provides access to s3 if that helps.

**Comment by jstein-vr** [comment]
> Hi guys, I suggest adding S3 bucket as an option as data origin. regards

I believe Kendra provides provides access to S3 if that helps.

**Comment by massi-ang** [comment]
RAG sources added to the solution must provide at least `retrieve` API that supports sematic search (vector search). Amazon S3 does not provide such API hence cannot be added directly as a source. 
All RAG sources that are currently included in the solution use S3 as the document storage service, ie when you upload a document to the workspace, it is stored in S3 and then parsed and indexed in the rag engine associated to the workspace.

**Comment by T4cceptor** [comment]
I think it might be a nice idea to be able to choose an S3 as data source when creating a workspace.
The rest could stay the same, but instead of creating a new bucket you would use the provided one.

**Comment by T4cceptor** [comment]
@massi-ang additional sources sound great, just not sure how it would work with access to those.

Yeah having the option to "import" files from S3 or a local folder would definitely be very helpful. Sounds great.
