### ISSUE TITLE
Bug: npm run deploy triggers large volume of code formatting changes

### ISSUE THREAD

**Issue by flamingquaks** [aws-samples/aws-genai-llm-chatbot#230]
Currently, I'm leveraging `npm run deploy` for the CDK deployment. As part of the call, the command executes `npm run format` first, which handles file formatting. 

When the command executes, I'm seeing formatting changes being applied to many files, even ones I've never touched. While I can discard these changes, it creates a burden if I forget to stage changes I want to keep before running the command. 

As a contributor, I worry that I will create bloated commits with changes that aren't necessary. 

Can we review the formatting to formatting to avoid this?

![Screenshot 2023-11-21 at 08 45 55](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/40297962/2a92a183-6144-457b-9e13-b1f2bb507e4a)

![Screenshot 2023-11-21 at 08 51 17](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/40297962/ee4ac957-0517-4ebd-bf13-701595b0dc53)

![Screenshot 2023-11-21 at 08 51 40](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/40297962/ddb40147-353d-4eaf-a95a-8e4db4c6836a)

**Comment by massi-ang** [comment]
Thanks for reporting this. 

Formatting should be done on commit/pr and not on deploy.
