### ISSUE TITLE
Enhancement: Open document in new tab 

### ISSUE THREAD

**Issue by manuwaik** [aws-samples/aws-genai-llm-chatbot#233]
In the metadata provide a link that when clicked opens the document in a new tab. For Kendra we could take them directly to the excerpt by using the Kendra metadata `_excerpt_page_number {"LongValue":<PAGE NUMBER>}` .

For documents that don't support in browser viewing, download the document.

**Comment by bigadsoleiman** [comment]
Added to backlog through a similar issue that will cover all RAG engines: https://github.com/aws-samples/aws-genai-llm-chatbot/issues/84 

Closing this one.
