### ISSUE TITLE
Add check for endpoint quotas within deployment

### ISSUE THREAD

**Issue by hoodand** [aws-samples/aws-genai-llm-chatbot#244]
Deployment fails if not enough endpoint instances are allowed on the account
`The account-level service limit 'ml.g5.12xlarge for endpoint usage' is 2 Instances, with current utilization of 2 Instances and a request delta of 1 Instances. Please use AWS Service Quotas to request an increase for this quota`

Moreover the rollback fails when the kendra index can't be deleted
```
12:11:35 PM | DELETE_FAILED        | AWS::Kendra::Index                              | RagEngines/KendraRetrieval/Index
Customer 853826371866 LogicalIndex 8a576b13-2720-4382-9a9b-dd5fa2929ae5 is in state CREATING at the moment, thus cannot be deleted (Service: Kendra, Status Code: 400, Request ID: 45691acb-6a21-4499-a48e-20498eb6f94b)
```

Can we add a check to ensure that the right number of endpoint instances in the config are allowed on the account?

**Comment by massi-ang** [comment]
Such check would marginally improve the user experience requiring unnecessary complexity for implementing such checks for all the possible resourcees used by the solution. The check is already performed by CloudFormation at deployment time and the user can simply redeploy the stack once the quota has been increased.
