### ISSUE TITLE
3.1.5 -> 3.1.6 upgrade: Merge conflict marker encountered.

### ISSUE THREAD

**Issue by portisto** [aws-samples/aws-genai-llm-chatbot#245]
Hello, I'm getting the below messages when trying to deploy the new version:

<img width="681" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/19312855/ba240090-1c85-46f4-9d12-4b1a8acd54bf">

Any ideas on the resolution?

**Comment by portisto** [comment]
so, after manual conflic resolution on the above mentioned files, i get the same issues during the cdk deploy.

**Comment by massi-ang** [comment]
If you have done any manual changes to files in 3.1.5, you will need to resolve the merge conflicts when pulling the new version.
