### ISSUE TITLE
ListCustomModels operation: Operation unknown

### ISSUE THREAD

**Issue by morin-alex** [aws-samples/aws-genai-llm-chatbot#246]
At first, the application seemed unable to list available models from Bedrock with the following error message:
```
Error listing Bedrock models: An error occurred (InternalServerException) when calling the ListFoundationModels operation (reached max retries: 4): The system encountered an unexpected error during processing. Try your request again.
Error listing Bedrock models: An error occurred (ValidationException) when calling the ListCustomModels operation: Operation unknown
```

The Bedrock endpoint used in the SharedConfig parameter store entry was `https://bedrock-runtime.us-west-2.amazonaws.com`. It seems the ListCustomModels operation should call the "bedrock" endpoint and not "bedrock-runtime". In this case, the lambda function ChatBotApiRestApiApiHandler was impacted.

After changing the endpoint to `https://bedrock.us-west-2.amazonaws.com`, the application had a second issue with the lambda function LangchainInterfaceRequestHandler:
```
ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The requested operation is not recognized by the service.
```

To fix this I had to divide the SharedConfig parameter store item into 2 separate items, one for the ChatBotApiRestApiApiHandler lambda function with the "bedrock" endpoint and a second one for the LangchainInterfaceRequestHandler lambda function with the "bedrock-runtime" endpoint.

**Comment by spugachev** [comment]
Hi, just delete endpointUrl from config.json and config.ts files

Before:
```
bedrock: {
  enabled: true,
  region: [SupportedRegion.US](http://supportedregion.us/)_EAST_1,
  endpointUrl: "https://bedrock-runtime.us-east-1.amazonaws.com/",
},
```

After:
```
bedrock: {
  enabled: true,
  region: [SupportedRegion.US](http://supportedregion.us/)_EAST_1
},
```

**Comment by morin-alex** [comment]
Hello,
I did remove the endpoint at first, and the parameter store item looked like this:
`{"prefix":"","bedrock":{"enabled":true,"region":"us-west-2","endpointUrl":""}`

But I ended up having the second issue with the LangchainInterfaceRequestHandler lambda function.
