### ISSUE TITLE
Model list has models that shouldn't be an option

### ISSUE THREAD

**Issue by QuinnGT** [aws-samples/aws-genai-llm-chatbot#259]
Not sure why just yet but the model's list is showing models like Claude 2:1:0:18K, Claude 2:1:0:200K, and Claude 2:1 when that isn't even a selectable model in bedrock.

Screenshot:
![Screenshot 2023-12-10 221400](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/44334535/cfe42f43-4520-4597-b296-96a8957c2023)

**Comment by bigadsoleiman** [comment]
Fixed with https://github.com/aws-samples/aws-genai-llm-chatbot/pull/275
