### ISSUE TITLE
Upgrade cdk

### ISSUE THREAD

**Issue by orangewise** [aws-samples/aws-genai-llm-chatbot#260]
Good morning,

it would be nice to upgrade the cdk to 214 so we can disable standby replicas in the OpenSearch vector db. This will help to save some costs during development:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchserverless.CfnCollection.html

https://aws.amazon.com/blogs/aws/vector-engine-for-amazon-opensearch-serverless-is-now-generally-available/

**Comment by bigadsoleiman** [comment]
#266 Merged
