### ISSUE TITLE
Feature request: Anthropic Claude 2.1 model

### ISSUE THREAD

**Issue by ajaylamba-provar** [aws-samples/aws-genai-llm-chatbot#261]
Anthropic Claude 2.1 is available on AWS Bedrock now. It should be available on the model list of the chatbot so that users can utilise this new and upgraded model.

**Comment by massi-ang** [comment]
Claude 2.1 is available in the model list.

**Comment by ajaylamba-provar** [comment]
@massi-ang The current prompt template in claude.py does not work well with claude 2.1 model. We should have separate prompt template for claude 2.1 utilizing system prompts as well.
