### ISSUE TITLE
Number of Chunk analyzed for the answer

### ISSUE THREAD

**Issue by GiuseppeSergi3** [aws-samples/aws-genai-llm-chatbot#262]
checking the metadata I saw that a fixed number of chunks (3) is considered for processing the response. 
Is it possible to change it?
Where is the part of code that sets this setting?

**Comment by massi-ang** [comment]
You can change the number of documents to be used in this line of code:

https://github.com/aws-samples/aws-genai-llm-chatbot/blob/6492f59efc9e2b56ddc00f7630780ef0b3d6ba4e/lib/shared/layers/python-sdk/python/genai_core/langchain/workspace_retriever.py#L14
