### ISSUE TITLE
User is not signed out even after days/hours of inactivity

### ISSUE THREAD

**Issue by ajaylamba-provar** [aws-samples/aws-genai-llm-chatbot#263]
User remains logged in into the app even after days/hours of inactivity. This poses a security risk.
User should be logged out automatically after a certain time period of inactivity.

**Comment by massi-ang** [comment]
User pool refresh token is set to 30 days validity by default. 
To set a shorter validity modify the CDK construct to add your own duration in the following construct: https://github.com/aws-samples/aws-genai-llm-chatbot/blob/6492f59efc9e2b56ddc00f7630780ef0b3d6ba4e/lib/authentication/index.ts#L23-L30


```
    const userPoolClient = userPool.addClient("UserPoolClient", {
      generateSecret: false,
      authFlows: {
        adminUserPassword: true,
        userPassword: true,
        userSrp: true,
      },
      refreshTokenValidity: cdk.Duration.days(1)
    });
```

**Comment by ajaylamba-provar** [comment]
@massi-ang Thanks, will try this.
