### ISSUE TITLE
Issue with special character present into filename submitted for rag process

### ISSUE THREAD

**Issue by hghandri** [aws-samples/aws-genai-llm-chatbot#264]
Hi,

we detected an issue when we uploaded its seems provoked by a file with name contain a special character like accent.

Here the extract log from step function : 

"Status": "FAILED",
  "StatusReason": "Environment variable value must be normalized according to Unicode Normalization Form C"

Did you face an issue like this ?

**Comment by massi-ang** [comment]
Can you provide a file to reproduce the issue?

**Comment by hghandri** [comment]
Hi,

you can try whit this file.
I've just tried another test right now and unfortunately it gave a same error.

[caractère-spéciale-éàè.pdf](https://github.com/aws-samples/aws-genai-llm-chatbot/files/13726459/caractere-speciale-eae.pdf)
