### ISSUE TITLE
Display only active Bedrock models

### ISSUE THREAD

**Issue by bigadsoleiman** [aws-samples/aws-genai-llm-chatbot#267]
Leverage `FoundationModelLifecycle` to filter out `LEGACY` models. [API Ref](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_FoundationModelLifecycle.html)

**Comment by massi-ang** [comment]
@bigadsoleiman Hi Bigad, are you working on this?

**Comment by bigadsoleiman** [comment]
Not yet
