### ISSUE TITLE
404 Error: Cannot access Bedrock models

### ISSUE THREAD

**Issue by ajaylamba-provar** [aws-samples/aws-genai-llm-chatbot#270]
Recently I experienced an issue where no model was returned by Bedrock API (/api/v1/models). The models list is coming as empty while all the other APIs like /workspaces etc are running fine.

After checking the logs for RestAPIHandler lambda, I noticed following errors:
Error listing Bedrock models: An error occurred (404) when calling the ListFoundationModels operation: <UnknownOperationException/>
Error listing Bedrock models: An error occurred (404) when calling the ListCustomModels operation: <UnknownOperationException/>

The same code was working yesterday but is not working today and there is no change in the AWS deployment. Seems like an issue from Bedrock side but not sure.

**Comment by massi-ang** [comment]
Hi,

thanks for reporting this. I have run a quick verification and everything seems to be working fine in my deployment.
Which kind of account are you using for the deployment? Can someone have implemented an SCP (Service Control Policy) that would block access to Bedrock APIs? Can you verify if you can access the Bedrock APIs in the account and region you have deployed the solution?

**Comment by ajaylamba-provar** [comment]
@massi-ang I have a separate dev account in my organisation where the solution is deployed and no one else is working on that account except me. So chances are less that someone else has made changes on AWS account.
I am able to access Bedrock playground in that account and the region via AWS console.

**Comment by massi-ang** [comment]
Hi Ajay, 

thanks for the clarification. Can you confirm this is still an issue when using the **Models** page in the UI? Can you please share the full error message you are getting?

**Comment by ajaylamba-provar** [comment]
Hi @massi-ang, yes this is still an issue when using Models page in the UI. Below is the screenshot:
<img width="1401" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/92162678/50ca7d4b-19cd-45e9-b497-5f5c7968cd99">

The error message in the logs is just that line. Here is the screenshot reference for the same.
<img width="1404" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/92162678/c61fb47e-cdc4-46a2-8afe-70bb21948c49">

**Comment by massi-ang** [comment]
Thanks. Which region are you using? Have you tried to use `boto3` directly to invoke those APIs? Can you please perform the test and report also the boto3 version used?

**Comment by massi-ang** [comment]
Can you also ensure you have updated the solution to the latest version? Beginning of December there has been a change in the Bedrock endpoints - the latest version fixes that.

**Comment by ajaylamba-provar** [comment]
@massi-ang Thanks for the heads-up about the changes in Bedrock endpoints. My solution is not upto date with changes made in December. It was working till yesterday with my current changes and there are no latest changes in last couple of days, so I didn't update it. I updated the cdk version though which is the last change.

I will try to sync with the latest changes.

**Comment by ajaylamba-provar** [comment]
I believe following changes are related to bedrock endpoint related issue:
https://github.com/aws-samples/aws-genai-llm-chatbot/commit/500575c54764e5e3d96c4157d37477edc254c266
https://github.com/aws-samples/aws-genai-llm-chatbot/commit/a2e56345bb75b8fa0860461aeba583484bd67cae

Is that correct @massi-ang ?

If yes, I will try to incorporate this fix.

**Comment by ajaylamba-provar** [comment]
@massi-ang Thanks for your help. The issue resolved after applying the above two fixes.
