### ISSUE TITLE
Feature: add Bedrock Knowledge Base as RAG Engine

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/aws-genai-llm-chatbot#271]
Bedrock provides a unified document retrieve API https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html that can be integrated to the solution. This would provide out of the box support for all the Vector stores supported by Bedrock.

**Comment by araker** [comment]
@massi-ang , any updates on this topic?
