### ISSUE TITLE
Integrate Anthropic Claude as an additional LLM

### ISSUE THREAD

**Issue by ibuchh** [aws-samples/aws-genai-llm-chatbot#28]
I believe we have an opportunity to elevate this project even further by considering integration with Anthropic Claude Language Model (LLM). With my prior experience, I can create the necessary code to seamlessly incorporate Anthropic Claude into our project. This integration would undoubtedly bolster our project's capabilities and offer our users a comprehensive and powerful experience.

**Comment by ibuchh** [comment]
Yes indeed.

**Comment by ishaan-jaff** [comment]
@ibuchh @massi-ang you can do this very easily using LiteLLM https://github.com/BerriAI/litellm/

it allows you to use any llm as a drop in replacement for gpt-3.5-turbo

**Comment by dairiley** [comment]
Anthropic Claude is available via Bedrock.
