### ISSUE TITLE
Code documentation to explain how different components of the solution are working together

### ISSUE THREAD

**Issue by azaylamba** [aws-samples/aws-genai-llm-chatbot#292]
It is challenging to understand the code flow for the features. And due to this, it is challenging to contribute as well because someone who is interested to contribute might not be able to understand at what all places changes are required.
For example, I want to contribute to #149 but it is not clear at what places the changes are required.

Having proper documentation would allow contributors to contribute more easily.

**Comment by bigadsoleiman** [comment]
We have ongoing effort for this now https://github.com/aws-samples/aws-genai-llm-chatbot/issues/305

Updates will be posted there
