### ISSUE TITLE
Prefix to differentiate this deployment - length limitation

### ISSUE THREAD

**Issue by aliaksei-ivanou** [aws-samples/aws-genai-llm-chatbot#293]
**App version:** 3.1.7
**Error message:** data|aws-genal-Ilm-chatbot-access-pol already exists in stack arn:aws:cloudformation:us-east-1:ACCOUNT_ID:stack/aws-genai-llm-chatbotGenAlChatBotStack/STACK_ID

**Findings:**
During the features configuration by running `npm run create`, I provided `aws-genai-llm-chatbot` as a value for the `Prefix to differentiate this deployment` configuration parameter. As a result, the stack deployment failed with the error `data|aws-genal-Ilm-chatbot-access-pol already exists in stack arn:aws:cloudformation:us-east-1:ACCOUNT_ID:stack/aws-genai-llm-chatbotGenAlChatBotStack/STACK_ID`. While the "sec-210" seems to be a safe value, longer values cause the mentioned error.
![image](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/27419521/0fd7bdf0-46a6-4614-99e4-05075e812968)

**Comment by bigadsoleiman** [comment]
Unfortunately each AWS resource has its own requirements in terms of format and length. 
It's not something we can really overcome unless deployer provides a shorter name.
