### ISSUE TITLE
Possibility to use custom domain name  with Cloudfront

### ISSUE THREAD

**Issue by hghandri** [aws-samples/aws-genai-llm-chatbot#298]
Hi,

do you have plan about managing a custom domain name with Cloudfront with secure protocol HTTPS of course.

Thanks.

**Comment by hghandri** [comment]
Hi 
I could implement this feature, it's  possible to talk about it at anytime to go further.

++

**Comment by azaylamba** [comment]
@hghandri A workaround for this is to add alternate domain name in cloudfront distribution.
