### ISSUE TITLE
Serve Query Responses from DynamoDB Conversation History

### ISSUE THREAD

**Issue by thejustin** [aws-samples/aws-genai-llm-chatbot#3]
Can you provide an option to serve responses only from the DynamoDB Conversation History? This way a user can cost optimize their usage of the ml.g5.24xlarge instance?

**Comment by bigadsoleiman** [comment]
Hi @thejustin checkout the new released version to achieve this. 

You can now integrate [custom](https://python.langchain.com/docs/modules/model_io/models/llms/custom_llm) or [fake](https://python.langchain.com/docs/modules/model_io/models/llms/fake_llm) LLMs. Without being forced to deploy a model on sagemaker. You can potentially have no LLM at all and still consult the conversation history and UI.

For a custom/fake LLM you will need to write your own [adapter](https://github.com/aws-samples/aws-genai-llm-chatbot/tree/main/lib/model-interfaces/langchain/functions/request-handler/adapters) like [this one](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/model-interfaces/langchain/functions/request-handler/adapters/openai/gpt.py) and simply return your preferred LLM object in `get_llm` method.
