### ISSUE TITLE
Request to service failed for Sagemaker endpoint creation

### ISSUE THREAD

**Issue by calcac** [aws-samples/aws-genai-llm-chatbot#30]
Hi, 

I'm trying to enable llama2 70b chat, I added the configuration below to aws-genai-llm-chatbot-stack.ts but the cloudformation fails during endpoint creation (model and config went fine) with the error: Request to service failed. If failure persists after retry, contact customer support.
It works fine if created from sagemaker studio.

```
  const llama2chat = new SageMakerModel(this, 'LLamaV270bChat', {
      vpc: vpc.vpc,
      region: this.region,
      model: {
        type: DeploymentType.ModelPackage,
        modelId: 'meta-textgeneration-llama-2-70b-f',
        instanceType: 'ml.g5.48xlarge',
        packages: (scope) =>
          new cdk.CfnMapping(scope, 'Llama2ChatPackageMapping', {
            lazy: true,
            mapping: {
              'eu-west-1': { arn: 'arn:aws:sagemaker:eu-west-1:985815980388:model-package/llama2-70b-f-v4-38616f307d8b3fcebba49bd88e19888c' }
            },
          }),
      },
    });
    // Make model interface aware of the sagemaker endpoint and add the necessary permissions to the lambda function
    langchainInterface.addSageMakerEndpoint({
      name: 'LLama2-70b-chat',
      endpoint: llama2chat.endpoint,
    });
```

Do you have any suggestion on what could be the issue? Thank you

**Comment by dairiley** [comment]
@calcac The error could be caused by a number of things (such as account limitations, deploying with a non-existing role) but it is hard to debug without additional information. You can check the reason for failure in the SageMaker Console or by checking the FailureReason field when running [describe-endpoint](https://docs.aws.amazon.com/cli/latest/reference/sagemaker/describe-endpoint.html) with the AWS CLI.

**Comment by gonzobrandon** [comment]
I think this failed for me becauset he mapping was tied to the `eu-west-1` region. I am looking for hte mapping in the `us-east-1` region.

**Comment by simonje** [comment]
It seems we need access to a publicly accessible model-package in the deployed region. I am looking for the us-west-2 one. Is there a documented list?

**Comment by cmilanf** [comment]
I am facing the same issue for `eu-west-1` region when trying to deploy `Llama2-70b-chat`, getting the error `Request to service failed. If failure persists after retry, contact customer support.` in the `FailureReason` after checking the endpoint with `describe-endpoint`. Code is very similar to @calcac one:

```
const llama2chat = new SageMakerModel(this, 'LLamaV2Chat', {
      vpc: vpc.vpc,
      region: this.region,
      model: {
        type: DeploymentType.ModelPackage,
        modelId: 'meta-LLama2-70b-chat',
        instanceType: 'ml.g5.48xlarge',
        packages: (scope) =>
          new cdk.CfnMapping(scope, 'Llama2ChatPackageMapping', {
            lazy: true,
            mapping: {
              'eu-west-1': { arn: 'arn:aws:sagemaker:eu-west-1:985815980388:model-package/llama2-70b-f-v4-38616f307d8b3fcebba49bd88e19888c' },
            },
          }),
      },
    });
    langchainInterface.addSageMakerEndpoint({
      name: 'LLama2-70b-chat',
      endpoint: llama2chat.endpoint,
    });
```
I cross checked the Model Package ARN is the correct one via deploying the model via SageMaker Jumpstart hub. As stated in this issue, deploying `13b` works fine.

**Comment by debdayal-aws** [comment]
Llama2 70b model package is not available to pull outside SageMaker JumpStart environment at this time. You can use the HuggingFace model and deploy it with HF TGI container. Below code snippet worked for me - 
`const Llama270bChat = new SageMakerModel(this, 'Llama270bChat', {
      vpc: vpc.vpc,
      region: this.region,
      model: {
        type: DeploymentType.Container,
        modelId: 'meta-llama/Llama-2-70b-chat-hf',
        container: ContainerImages.HF_PYTORCH_LLM_TGI_INFERENCE_LATEST,
        instanceType: 'ml.g5.48xlarge',
        containerStartupHealthCheckTimeoutInSeconds: 600,
        env: {
          SM_NUM_GPUS: JSON.stringify(8),
          MAX_INPUT_LENGTH: JSON.stringify(2048),
          MAX_TOTAL_TOKENS: JSON.stringify(4096),
          MAX_BATCH_TOTAL_TOKENS: JSON.stringify(8192),
          HF_MODEL_ID: 'meta-llama/Llama-2-70b-chat-hf',
          HUGGING_FACE_HUB_TOKEN: 'hf_xxxxxxx',
        },
      },
    });`
