### ISSUE TITLE
Pagination on documents-tab component is not working correctly

### ISSUE THREAD

**Issue by azaylamba** [aws-samples/aws-genai-llm-chatbot#304]
The pagination on the documents page of a workspace is not working correctly. Only the page number 1 is visible and hence the user is not aware about how many pages are there in total.

<img width="1275" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/22918086/154ce6e5-9414-4073-a440-5a59eedc78a2">

The number of pages should be visible clearly and the user should be able to click on the page number to navigate to that page. Can be implemented similar to how it is done for session history.

**Comment by bigadsoleiman** [comment]
Since we are using DDB we can't get total count unless we retrieve all documents in advance, which would be very inefficient.

Closing this as not planned.

**Comment by azaylamba** [comment]
I agree.

In order to make the UI explicit, can we add Next/Previous buttons instead of showing page number? This way, we can disable the next button when there no more pages left.

Also we should provide a search functionality so that users can search for the documents. But maybe this can be done separately.
