### ISSUE TITLE
Port existing documentation to vitepress site

### ISSUE THREAD

**Issue by dairiley** [aws-samples/aws-genai-llm-chatbot#305]
Existing documentation should be moved to the GitHub pages Vitepress documentation site to allow for clearer organization.

**Comment by ajaylamba-provar** [comment]
@bigadsoleiman @dairiley Should we add the link of documentation site on readme page as instructions are not easily accessible now after this change?

**Comment by dairiley** [comment]
The documentation site is linked under the 'Open in GitHub CodeSpaces' button in the README currently. We will make this clearer by giving it it's own button
