### ISSUE TITLE
ability disable use of chat history context in following answers

### ISSUE THREAD

**Issue by Rob-Powell** [aws-samples/aws-genai-llm-chatbot#306]
Sometimes users don't want to enable contextual awareness of the conversation and each question within the same window should be treated as independent.

It would be useful to be able to disable chat history context usage in formulating a reply, without affecting the logging of the chats.

**Comment by bigadsoleiman** [comment]
After review the best path forward would be to make it easier to create a new session instead of allowing no-history in conversation.

Closing in favour of https://github.com/aws-samples/aws-genai-llm-chatbot/issues/283
