### ISSUE TITLE
Add explicit history Icon to open the history panel + new conversation 

### ISSUE THREAD

**Issue by azaylamba** [aws-samples/aws-genai-llm-chatbot#311]
We are using tools drawer of `AppLayout` for displaying user session history. The icon for tools drawer is Info icon which does not represent history, so end user might find it inconvenient to locate the session history. The icon is not customizable intentionally as mentioned [here](https://github.com/cloudscape-design/components/issues/1891).

We should use secondary panels like [Drawer](https://cloudscape.design/components/drawer/) for displaying session history.

**Comment by bigadsoleiman** [comment]
Possibly add a new button to create a new session from https://github.com/aws-samples/aws-genai-llm-chatbot/issues/283

**Comment by azaylamba** [comment]
New Sessions menu is added as part of https://github.com/aws-samples/aws-genai-llm-chatbot/pull/433.

Closing this issue.
