### ISSUE TITLE
Getting error "'Router' object has no attribute '_resolvers'"

### ISSUE THREAD

**Issue by azaylamba** [aws-samples/aws-genai-llm-chatbot#340]
I am trying to migrate from earlier version of the code to latest where we are using AppSync and GraphQL. After deploying the app, I am getting following error in all the requests being made from UI.

<img width="672" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/22918086/71bcf0eb-789c-45c1-b80a-8d71472204ad">

I might have missed something while merging the conflicts. Any help in resolving this error would be greatly appreciated.

**Comment by azaylamba** [comment]
@massi-ang Could you please give some pointers about what I might be missing?

**Comment by Rob-Powell** [comment]
@azaylamba You mean you are trying to migrate from a pre appsync version to the newer version now with appsync?
This is a major breaking change and there is not a documented upgrade path. The current advice is users need to re-deploy

**Comment by azaylamba** [comment]
@Rob-Powell Yes, I am migrating from pre appsync to the newer version. And I have re-deployed the app with a new prefix.

**Comment by azaylamba** [comment]
I found the reason, one of my api handler router file was still having older import statement for **Router** (`from aws_lambda_powertools.event_handler.api_gateway import Router`) and this router was being included in `AppSyncResolver`.
The error thrown on console was misleading and hence was not able to pinpoint the issue. Trying to debug the lambda function in VS code with a sample HTTP redirect request with AWS Toolkit helped in finding the root cause as error was visible on console as in why the sample request got failed.

On a side note @Rob-Powell, could you please help me with any proper documentation on how to debug the lambda functions in VS Code?

**Comment by azaylamba** [comment]
Closing the issue as the problem was incorrect use of import statement for Router. The correct import statement now with appsync is `from aws_lambda_powertools.event_handler.appsync import Router`
