### ISSUE TITLE
feat(cli): add option to indicate an existing VPC ID

### ISSUE THREAD

**Issue by bigadsoleiman** [aws-samples/aws-genai-llm-chatbot#345]
- Update magic-create in order to ask to use a brand new or existing VPC

**Comment by surukonda** [comment]
@bigadsoleiman I can work on this. I also raised another feature request [389](https://github.com/aws-samples/aws-genai-llm-chatbot/issues/389) to specify aurora default database name, I can work on both of these.

**Comment by spugachev** [comment]
@bigadsoleiman are you working on it? If not, let's accept @surukonda's contribution

**Comment by bigadsoleiman** [comment]
I'm not. Any non-assigned and help-wanted marked issues can be picked up. 
So @surukonda if it's still the case please confirm and feel free to go on. 

Thanks

**Comment by surukonda** [comment]
> I'm not. Any non-assigned and help-wanted marked issues can be picked up. So @surukonda if it's still the case please confirm and feel free to go on.
> 
> Thanks

@bigadsoleiman Please assign it to me.

**Comment by bigadsoleiman** [comment]
Done! thanks

**Comment by surukonda** [comment]
@bigadsoleiman I can also work on #389, let me know.

**Comment by surukonda** [comment]
@bigadsoleiman  this can be closed.
