### ISSUE TITLE
Issue: RAG source undefined in chatbot when selecting the LLM before the RAG source

### ISSUE THREAD

**Issue by louwarnett** [aws-samples/aws-genai-llm-chatbot#35]
In the chatbot, when entering a question, then selecting the LLM to use and finally the RAG source, the chosen RAG source is not used. In the `"run"` action, viewable from the browser console, the `ragSource` is `undefined`. In contrast, when entering a question, then selecting the RAG source and finally the LLM, the `ragSource` is passed as normal. It therefore appears that there is a UI bug.

**Comment by bigadsoleiman** [comment]
This is fixed in the latest release `v3.0.0`
