### ISSUE TITLE
Why does app.tsx directly import infrastructure config?

### ISSUE THREAD

**Issue by dfkunstler** [aws-samples/aws-genai-llm-chatbot#360]
https://github.com/aws-samples/aws-genai-llm-chatbot/blob/bb0fe2384b7264caa7c61743ee5557f216559f9c/lib/user-interface/react-app/src/app.tsx#L19

I believe the reference above was introduced in 4.0.2. 

My question is, why create an explicit dependency on `config.json`, which isn't part of the source tree, when a default config available? Obviously we expect people to generate a config, but prior to this release it was possible to do a clean build from source using the default config produced by config.ts:
https://github.com/aws-samples/aws-genai-llm-chatbot/blob/bb0fe2384b7264caa7c61743ee5557f216559f9c/bin/config.ts#L6

IMO that default config mechanism is important. It gives us a way to test that a new release works as shipped before introducing local config (typically generated by a previous release). Then if build fails for any reason, we can easily determine if previous local config is the source of the trouble.

I assume that it was implemented this way to avoid a dependency between runtime app code and infrastructure code, and i certainly support that choice. If that's the case, then i'd argue it should extend also to configuration files. Application runtime config should separate from infrastructure config (as in the aws-exports.json file). 

Apologies in advance if i've misunderstood something. Thanks for taking the time to explain.

**Comment by bigadsoleiman** [comment]
Hi @dfkunstler thanks for pointing this out
importing a file from the CDK domain into the react-app domain was simply wrong.

This has been addressed with https://github.com/aws-samples/aws-genai-llm-chatbot/pull/367
