### ISSUE TITLE
Feature: Improve github actions with cdk synth

### ISSUE THREAD

**Issue by QuinnGT** [aws-samples/aws-genai-llm-chatbot#362]
**Issue:**
With more and more contributions, I don't think they are getting fully tested before being merged. 

**Proposed Solution:**
Expand build.yaml to include github action [cdk synth](https://github.com/marketplace/actions/aws-cdk-github-actions) to validate changes as part of PR process.

I think you can run cdk synth without aws credentials but worst case this would require AWS account keys to be added to github secrets but maybe this is something we could get added for internal AWS sample product support?

**Comment by dairiley** [comment]
Hi, I am currently working on e2e testing for the stack that will run as a GitHub action. This will offer the same protection as running cdk synth, but with more granularity. I've made an issue: #364 that you can track for updates.
