### ISSUE TITLE
Provide best effort cost estimation for the solution

### ISSUE THREAD

**Issue by lynnna-xu** [aws-samples/aws-genai-llm-chatbot#37]
I greatly appreciate the dedication of individuals who contribute to this field. Recently, I decided to explore AWS using my personal account. Aware of potential costs associated with certain AWS services, I took the precaution of removing the bedrock and SageMaker-related modules, and deploying a 3P-model-only solution.

However, I encountered an unexpected situation when my account incurred substantial expenses related to the OpenSearch service. I was thinking OpenSearch Service supports a free tier trial. To my surprise, my bill statement showed charges for IndexingOCU and SearchOCU, each costing $0.24 per OCU-hour. These charges accumulated to more than $20 per day (You will be billed for a minimum of 4 OCUs (2x indexing includes primary and standby, and 2x search includes one replica for HA) for the first collection in an account), even when there was no actual utilization of the service.

While I acknowledge that gaining a deeper understanding of AWS fee schedules is advisable, I believe it's important to highlight this issue. It's worth noting for individuals who simply wish to experiment with AWS services that unexpected costs can arise. It would be highly beneficial if sample solutions could default to free-tier or low-cost configurations, enabling users to increase capacity as needed, thereby preventing inadvertent high expenses.

Thanks again for the great work.

**Comment by sudamerushabh** [comment]
Hi. What is the cost associated with the solution?

There is no mention of cost and I am hesitating because of that.

**Comment by bigadsoleiman** [comment]
Thanks @lynnna-xu and @sudamerushabh, I've renamed the issue with the goal of featuring some kind of cost estimation.

It won't be perfect given the matrix of features that can be selected/deselected and that not all services are available in https://calculator.aws/#/ yet but it will be a starting point.

**Comment by QuinnGT** [comment]
One idea here is to add the cost estimation to the create script so as users are picking each feature it shows estimated cost by feature and then totals at the end.
