### ISSUE TITLE
cdk deploy fails on ChatBotApi/ChatBuckets/FilesBucket 403

### ISSUE THREAD

**Issue by mcsp-emendo** [aws-samples/aws-genai-llm-chatbot#370]
I am stuck on setting this up, and getting error:
`6:35:52 PM | CREATE_FAILED        | AWS::S3::Bucket                                 | ChatBotApi/ChatBuckets/FilesBucket
Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID: QH2EWTSPAA79KZMZ, Extended Request ID: VHA+IN4N
GqCWPPKz4ls+4ROKhB6ieefK1fRp7AdPuse8af9630zRBiGYG3l5s+Jd1j8q3S5gz4jvWoifiKcPOw==)" (RequestToken: 818e9c4c-b352-361b-c0e9-d9954a16ebdd, Handl
erErrorCode: GeneralServiceException)`

**Comment by kzaini** [comment]
I'm having the same issue. Any ideas on how to solve?

**Comment by mcsp-emendo** [comment]
For me the issue was that my account needed to be verified by amazon to be able to create cloudfront distributions.
I tried commenting out https://github.com/aws-samples/aws-genai-llm-chatbot/blob/e56f097350a378c3e5669eabc534a48ec230c6b8/lib/chatbot-api/chatbot-s3-buckets/index.ts#L24C1-L24C32 and it could now create the bucket, but then would fail on setting up a cloudfront distribution. Ater creating a ticket for account verification all worked.

**Comment by azaylamba** [comment]
I am getting exactly same error while trying to deploy this in my personal account. Checked everything related to IAM role permissions, SCL etc and everything seems fine there. I have raised ticket as suggested above, waiting for the reply.
Below is the error message:

CREATE_FAILED        | AWS::S3::Bucket                                 | RagEngines/DataImport/UploadBucket
Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID: KGE7XHN9KKK51FRG, Extended Request ID: bSoUl1pXiNDjBsP1PLUAsjWORQaCNQkWXUWv4nMvGmvo+pvUbXoOu3OUCKfW4lrs/IVI7qwvnJ
A=)" (RequestToken: e8a1a9a3-f245-e4bd-8cff-4898d51f1ea1, HandlerErrorCode: GeneralServiceException)

**Comment by azaylamba** [comment]
The issue is indeed related to account verification. I am able to deploy the app once the AWS support team verified my account. I had to raise a ticket for the same.

The exception is misleading though and don't give enough information about the actual problem.
