### ISSUE TITLE
LLM overwrites previously written text during streaming

### ISSUE THREAD

**Issue by nickbiso** [aws-samples/aws-genai-llm-chatbot#371]
I notice that while streaming an LLM message it tries to correct previously written words while its finishing its response. In the first line of the below screenshot notice how it says "Amazon web services (AWS) is a cloud platform" and later on it gets replaced with 
"Amazon web services (AWS) is a cloud computing platform".  I have also seen that sometimes it already finished the message however, after a few seconds its changing some words in the response. These behavior is not experienced in the Bedrock console. It is possible that this is related to a previous bug: https://github.com/aws-samples/aws-genai-llm-chatbot/issues/341

Mid streaming:
<img width="1687" alt="Pasted Graphic" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/16202142/1b21538e-c43d-4cbc-8c56-b0eabc43e06b">

After streaming:
<img width="1670" alt="Pasted Graphic 1" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/16202142/6eac44d5-412d-45bc-a2ca-e5d11668623a">

Let me know if you have any questions.

**Comment by azaylamba** [comment]
Also, the streaming response is not consistent/correct until whole answer is displayed which makes it difficult to read the answer. The words are inserted in between the previously written words which are jumbled up. The answer is in correct state to read only after the streaming is complete.
