### ISSUE TITLE
Enhancement: record full prompt in the feedback record

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/aws-genai-llm-chatbot#374]
The user feedback feature introduced in #287 records the user feedback with the following format:

```
{"feedbackId": "d7911ac5-36e1-449e-ba27-766bb1fdb997", "sessionId": "7d78bb7c-dfd6-4b70-b16c-fd34af42b435", "userId": "xxxxx", "key": "5", "prompt": "About Charle Magn", "completion": "  Sure, I can help with that! Here's a brief overview of Charles Magn:\n\nCharles Magn was a French inventor and engineer who is best known for his work on the first practical typewriter. He was born in 1827 and died in 1909. Magn's typewriter was patented in 1874 and featured a QWERTY keyboard layout that has since become the standard for typewriters and computer keyboards.", "model": "meta.llama2-13b-chat-v1", "feedback": "1", "createdAt": "2024-02-12T21:37:47.881565Z"}
```

Note that the `prompt` field contains only the user question, and not the full prompts sent to the LLM, which would consist of a prompt template formatted with the chat history and the user question. 

By only recording the user question, the data will not be useful for fine tuning of the model.

We want to record the full prompt, and possibly also the prompt template and template arguments values.

**Comment by massi-ang** [comment]
@azaylamba Hi Ajay, would you like to take a stab at this since you submitted the PR on user feedback?

**Comment by azaylamba** [comment]
Sure @massi-ang, I will look into this in a couple of days.

**Comment by canada4663** [comment]
I think this one can be closed with merge last week
