### ISSUE TITLE
Feature request: Expose consumable APIs

### ISSUE THREAD

**Issue by azaylamba** [aws-samples/aws-genai-llm-chatbot#382]
Consumable APIs would ensure that the chatbot functionality can be accessed by other products via APIs. It would make the integration with other products easy.

**Comment by azaylamba** [comment]
@massi-ang @bigadsoleiman are there any plans for such feature in the future?

**Comment by ystoneman** [comment]
Could you please share:

- Required functions to expose initially (e.g., just query and response)?
- Primary use case (e.g., integrating the chatbot into your own UI) -- anything specific you could share?
- Performance or scalability requirements?

**Comment by azaylamba** [comment]
@ystoneman 
 The initial requirement is to ask questions and get responses. And maybe authentication as well so that only authenticated users can call the APIs.
Primary use case is the ability integrate the chatbot into multiple products (e.g. web app having own UI, mobile, desktop app etc).
The APIs should be able to handle moderate load (e.g. 100 users calling the APIs simultaneously).
