### ISSUE TITLE
Incorrect link in README kendra section

### ISSUE THREAD

**Issue by swarwick** [aws-samples/aws-genai-llm-chatbot#39]
The Kendra section mentions a "Click here" to find out how to enable it. This link is currently going to line 206 in the aws-genai-llm-chatbot-stack.ts which does not appear to be related to Kendra at all.

**Comment by swarwick** [comment]
After looking this over I understand a bit more on why it points to this area in the file which is commented out code. It might be a bit more user friendly to point to a header code block that explains a bit on how to pull out the kendra section to use vs all the RAG items.

**Comment by bigadsoleiman** [comment]
With the release of `v3.0.0` we are now providing a handy CLI tool that guides you in the configuration of the solution before deploying without the need to comment/uncomment code.

More details [here](https://github.com/aws-samples/aws-genai-llm-chatbot#deployment)
