### ISSUE TITLE
uploading a pdf file takes a long time

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#394]
Dear all,

I have created a Workspace with all default settings and tried to upload a pdf file of ~54 MB (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-ug.pdf)

The uploading task is not finished since then and is still running (around 4 hours already).

Is it normal behavior ?
If not, what is the way to troubleshoot such issues ?

best regards
Alexey Shishkin

**Comment by alexeyshishkin01** [comment]
Another example is uploading a 12 MB pdf-file https://docs.aws.amazon.com/dms/latest/userguide/dms-ug.pdf took me 22 minutes, so around 9,3 KB (kilobyte) per second.
Is such speed expected ?

**Comment by ystoneman** [comment]
Hi Alexey, please share more setup details to resolve the slow PDF upload. Have you tried another network? Are other PDFs also slow or just those two? Any errors or logs that explain hanging uploads?

You linked full DMS and RDS guides. Were those example PDFs or relevant to the issue?

**Comment by alexeyshishkin01** [comment]
my answers to the questions:
- 'please share more setup details' - the setup is simple to reproduce: RAG-engine is Aurora, all options are by default
- 'Have you tried another network ?' - what network do you mean ?
- 'Are other PDFs also slow or just those two' - I did not try other files so far. I try to upload bigger files not exceeding the limit (100MB). Is it possible for you to follow my steps ?
- 'any errors or logs that explain hanging uploads ?' - UI doesn't provide any errors, pls. let me know where the logs are located ?
- 'You linked full DMS and RDS guides. Were those example PDFs or relevant to the issue?' - could you pls. clarify your question ?
