### ISSUE TITLE
Feature request: Indicate if a document is being used for a response

### ISSUE THREAD

**Issue by pbv0** [aws-samples/aws-genai-llm-chatbot#4]
When using the semantic search stack, it would be great to see if the uploaded documents are being used in a response (and which document was used to inform the answer).

**Comment by bigadsoleiman** [comment]
Hi @pbv0,

as part of the [new release of today](https://github.com/aws-samples/aws-genai-llm-chatbot/releases/tag/v.2.0.0), when semantic search is used, you will be able to see documents and text excerpt injected in the prompt. 

You can see it in action [here](https://github.com/aws-samples/aws-genai-llm-chatbot#multiple-rag-sources).
