### ISSUE TITLE
Response length is being truncated - LLM titanxl- where can this be configured?

### ISSUE THREAD

**Issue by scottmraz** [aws-samples/aws-genai-llm-chatbot#40]
Responses are being truncated even using titan xl. Is there a way to configure the response length? It doesn't exceed Titan's token output length.  

![2023-09-14_17-17-22](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/70114968/ea89889b-66a0-4d6e-a323-057b0de1125b)

**Comment by swarwick** [comment]
I noticed this as well, does this have to do with streaming vs not?

**Comment by bigadsoleiman** [comment]
I suspect it uses a default amount of tokens given that the only parameter is passed through is the `temperature` for the [titan adapter](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/e4ad12f4145624290123cd41b5ebdb806daaf8fb/lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/titan.py#L27)

All model params are handled in the related adapter now, we are working to expose at least most common model parameters in the UI

The param for Titan should be `maxTokenCount`

**Comment by bigadsoleiman** [comment]
With the release of `v3.0.0` is now possible to set the Max Tokens from the UI

![image](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/83646217/91eba74d-7476-4df8-89a3-fe2ff70134ee)

**Comment by scottmraz** [comment]
Nice, ty!
