### ISSUE TITLE
Show tokens consumption and estimated cost for chat and multi-chat playground 

### ISSUE THREAD

**Issue by brnaba-aws** [aws-samples/aws-genai-llm-chatbot#410]
Currently, there is no indication about the cost related to the call of an LLM.
It would be interesting to understand how much the message affects the cost of invoking a LLM but it would be even more interesting when comparing models one to another.
In this picture, the cost could be displayed at the bottom, but it could also be part of the metadata section.

<img width="1137" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/64135631/a27ce61d-a6da-4513-a0f8-dd22b67019d0">

**Comment by ystoneman** [comment]
Great idea, @brnaba-aws! 

1. Do you think it would be useful to toggle this "cost insights" feature off and on in the settings?
2. Do you think it would be useful to show both the individual message cost (like in your awesome mockup) _and_ the overall conversation cost?
3. Do you have any favorite frameworks/libraries that you'd recommend for implementing components of this feature?

Please feel free to contribute a draft pull request if you'd like to work on this -- all contributions welcome! And I'm ready to support you in that process.
