### ISSUE TITLE
Feature: Fine-tuned Models in Bedrock

### ISSUE THREAD

**Issue by arm-diaz** [aws-samples/aws-genai-llm-chatbot#42]
Can we add support of fine-tuned models?

The following code snippet could be added in [list_bedrock_models()](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/model-interfaces/langchain/functions/request-handler/models.py):

```py
        response_custom_models = bedrock.list_custom_models()
        bedrock_custom_models = response_custom_models.get("modelSummaries", [])        
        custom_models = [
            {
                "provider": "bedrock",
                "modelId": model["modelName"],
                "streaming": False,
                "type": "text-generation",
            }
            for model in bedrock_custom_models
            if (
                model["modelName"].startswith("<<fine-tuned-model-prefix>>")
            )
        ]
        models.extend(custom_models)
```

In addition, it should include an error handler for API requests.

**Comment by bigadsoleiman** [comment]
With the release of `v3.0.0` we also list [custom models](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/0c71910550cf510285fe4f140c4b4654526df39a/lib/shared/layers/python-sdk/python/genai_core/llms.py#L13) from Bedrock
