### ISSUE TITLE
Prevent deployment/show warning when Default VPC is imported

### ISSUE THREAD

**Issue by teearem** [aws-samples/aws-genai-llm-chatbot#428]
facing an error in my cloud9 console when i run "npm cdk deploy"; Error: Lambda Functions in a public subnet can NOT access the internet. If you are aware of this limitation and would still like to place the function in a public subnet, set `allowPublicSubnet` to true
![Uploading Screenshot 2024-03-21 at 2.29.58 PM.png…]()

**Comment by bigadsoleiman** [comment]
This is happening when Default VPC is imported in CLI. Default subnets are public.
We should probably prevent deployment/show a warning message before as some resources needs to be in private subnet for security reasons
