### ISSUE TITLE
Deploy error as SSM parameter not found

### ISSUE THREAD

**Issue by pchaganti** [aws-samples/aws-genai-llm-chatbot#429]
Using the latest repo version. Doing a deploy results in this error.

```
 ❌ Deployment failed: Error: testGenAIChatBotStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
    at Deployments.validateBootstrapStackVersion (/Users/pchaganti/Dev/test/node_modules/aws-cdk/lib/index.js:431:12220)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deployments.buildSingleAsset (/Users/pchaganti/Dev/test/node_modules/aws-cdk/lib/index.js:431:10985)
    at async Object.buildAsset (/Users/pchaganti/Dev/test/node_modules/aws-cdk/lib/index.js:431:194378)
    at async /Users/pchaganti/Dev/test/node_modules/aws-cdk/lib/index.js:431:178767

testGenAIChatBotStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
```

The environment is bootstrapped and the above mentioned "/cdk-bootstrap/hnb659fds/version" also exists. Screenshot from the console with the parameter below.

![image](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/6500/7241664b-c481-4146-bb04-d6fe81a061bd)

**Comment by pchaganti** [comment]
Anyone have any info on how to resolve this error?

thanks

**Comment by ssliman** [comment]
Hi @pchaganti

You can fix it by adding the `qualifier` to your `Pipeline` stack under the folder `/bin`:

`
const stack = new Pipeline(app, 'some-stack', {
  synthesizer: new cdk.DefaultStackSynthesizer({
    qualifier: 'prod',
  }),
});
`
This what worked for me. Using the qualifier with CLI doesn't force it.
