### ISSUE TITLE
next Kendra question even Kendra is not selected

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#432]
Dear all,

When I run 'npm run config' and select 'Aurora' as the only datastore (I don't select 'Kendra' as a datastore), the next question about Kendra is still here ('Do you want to add existing Kendra indexes (y/N)'):

:~/environment/aws-genai-llm-chatbot (main) $ npm run config

> aws-genai-llm-chatbot@3.1.3 config
> node ./cli/magic.js config

✔ Prefix to differentiate this deployment · genai
✔ Do you want to use existing vpc? (selecting false will create a new vpc) (y/N) · false
✔ Do you want to deploy a private website? I.e only accessible in VPC (y/N) · false
✔ Do you want to provide a custom domain name and corresponding certificate arn for the public website ? (y/N) · false
✔ Do want to restrict access to the website (CF Distribution) to only a country or countries? (y/N) · false
✔ Do you have access to Bedrock and want to enable it (Y/n) · true
✔ Region where Bedrock is available · us-east-1
✔ Cross account role arn to invoke Bedrock - leave empty if Bedrock is in same account ·
✔ Do you want to use any Sagemaker Models (y/N) · true
✔ Which SageMaker Models do you want to enable · FalconLite [ml.g5.12xlarge]
✔ Do you want to enable a start/stop schedule for sagemaker models? (Y/n) · false
✔ Do you want to enable RAG (y/N) · true
✔ Which datastores do you want to enable for RAG · aurora
? Do you want to add existing Kendra indexes (y/N) ‣ false

Is it correct ?
If not, could you pls. fix it, so that I don't answer next Kendra question when I don't select Kendra at all.

best regards
Alexey Shishkin

**Comment by massi-ang** [comment]
This is correct. This question is based on the fact that you have answered YES to `Do you want to enable RAG (y/N)`. The datastore to enable is related to creating new datastores managed by the Chatbot Demo, meaning that if you destroy the Chatbot stack those data stores are also removed. The question you point out is about adding existing Kendra indexes which are managed outside of the Chatbot Demo. 

Do you have any suggestion on how we could make it clearer for users?

**Comment by alexeyshishkin01** [comment]
From my (user) point of view if one does not select the 'Kendra' during the question 'Do you want to enable RAG (y/N), there should not be any further question about 'Kendra indexes', because 'Kendra' has not been selected previously.

Let me put it the other way: why does the user need to add existing Kendra indexes if the user does not select Kendra at all ?

**Comment by massi-ang** [comment]
As mentioned in my previous answer, the question for adding **existing** Kendra indexes is related to the choice you made to use RAG. Users might want to use existing Kendra indices instead of creating a new empty one, which is what happen if you select Kendra in the list of RAG engines. 

We'll look into using a better wording and add additional information to the documentation.

**Comment by alexeyshishkin01** [comment]
It looks like there is a misunderstanding, why a user would need to use existing Kendra indexes if the user did not choose Kendra as a RAG engine a moment ago ?
