### ISSUE TITLE
 "Uploaded file must be a non-empty zip 

### ISSUE THREAD

**Issue by fghorbel** [aws-samples/aws-genai-llm-chatbot#444]
Hello, 

I received the error below when i ran the following command: `npx cdk deploy`

 "Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 210457af-99bd-4cc0-8152-e1
123c16a141; Proxy: null)" (RequestToken: 45a936e2-4133-c661-a746-613f3b695863, HandlerErrorCode: GeneralServiceException)

**Comment by massi-ang** [comment]
Hi @fghorbel,
can you provide some additional information on the steps you performed so that we can try to reproduce the issue?

**Comment by gbone-restore** [comment]
I was able to reproduce this issue on a fresh local install. I was able to work around by making some changes to the bundler code in /Users/gregbone/Development/aws-genai-llm-chatbot/lib/layer/index.ts. I changed line 21 to the following:

``` 
    const args = ["-t", "/asset-output/python"];
```

Let me know if this works for others and I can do a PR.
