### ISSUE TITLE
how to run the deployment 'npx cdk deploy' without additional confirmation

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#445]
Dear all,

I am trying to automate the deployment, but unfortunately even if I use 'npx cdk deploy --all --force' there's still a need for for confirmation: 'Do you wish to deploy these changes (y/n)?'

If there's a way to run the deployment without additional confirmation ?

best regards
Alexey Shishkin

**Comment by massi-ang** [comment]
Try with `--method=direct`

**Comment by alexeyshishkin01** [comment]
according to the 'npx cdk deploy --help':

-m, --method   How to perform the deployment. Direct is a bit faster but lacks progress information [string] [choices: "direct", "change-set", "prepare-change-set"]

it does not specify anything about confirmation, but OK, let me try ...

on the other hand:
--all   Deploy all available stacks [boolean] [default: false]
-f, --force   Always deploy stack even if templates are identical [boolean] [default: false]

they are supposed to work, but they did not

**Comment by massi-ang** [comment]
I forgot to mention to add `--require-approval never`

**Comment by alexeyshishkin01** [comment]
So, what is going to be the final suggestion from your side ?

Is it 'npx cdk deploy --method=direct --require-approval never' ?

**Comment by alexeyshishkin01** [comment]
this is to confirm the command 'npx cdk deploy --method=direct --require-approval never' does the job
pls. update the documentation mentioning this command as a way to run deployment of the application non-interactively
