### ISSUE TITLE
Option to select the persona of chatbot

### ISSUE THREAD

**Issue by vikramshitole** [aws-samples/aws-genai-llm-chatbot#45]
Can we have a pre-built list of personas :
1. Health Advisor
2.  Finance Advisor 
3.  Insurance Advisor
etc

And specific Prompt mapped to the persona to get better results from the models and a way to tweak the Prompts.

**Comment by massi-ang** [comment]
Hi,

thanks for raising this enhancement request. We have considered the request and decided to address it in a more generic fashion via #72, to allow the generic customization of the prompts used by the solution. In this way one would be able to add prompts to achieve different personas.
