### ISSUE TITLE
S3 Bucket Name is Empty when deploying UI Bucket

### ISSUE THREAD

**Issue by gknorman-amazon** [aws-samples/aws-genai-llm-chatbot#450]
I tried deploying today with minimal input (with a private website only accessible in a VPC) during the config process, but the deployed CFN had an empty string for the S3 Bucket Name for the UI hosting bucket:

"UserInterfaceWebsiteBucket2BDEA247": {
   "Type": "AWS::S3::Bucket",
   "Properties": {
    **"BucketName": "",**
    "LoggingConfiguration": {
     "DestinationBucketName": {
      "Ref": "UserInterfaceWebsiteLogsBucket54728780"
     }
    }
    
 I didn't provide a certificate ARN nor a domain name, and I'm not sure if these are necessary to generate the Bucket Name, but I expected there to be an explicit step to name the bucket during configuration if input is actually needed from the user.

**Comment by gknorman-amazon** [comment]
In the meantime, I'll fix this the "wrong" way by creating a default bucket name in case the domain name is left empty during the config process in `user-interface/index.ts`

`const defaultBucketNameString = "website-bucket" + cdk.Stack.of(this).account + "-" + cdk.Stack.of(this).region; `
    
 `const defaultDomainName = props.config.domain ? props.config.domain : defaultBucketNameString;`

If I enter my own domain name but I haven't set up my own hosted zone, etc already, will it create it for me?  If so, I feel very silly and would ask for an update in config process or the documentation to make us aware of this.

**Comment by Rob-Powell** [comment]
As per the docs you need to do the pre req steps and then pass those values to the installer:

https://aws-samples.github.io/aws-genai-llm-chatbot/documentation/private-chatbot.html

**Comment by gknorman-amazon** [comment]
Can these prereqs be shown / linked to on the Deployment Guide page then?

This is the first time seeing this "Private Chatbot" page since I went straight from the "The Project" page and the "Deployment Guide" link at the bottom of that page.  I didn't realize there were any prereqs when I started the Cloud 9 deployment steps.

**Comment by Rob-Powell** [comment]
They are linked to on the left hand side navigation. but there should be validation on those fields in config creation.
