### ISSUE TITLE
PDF upload fails with spaces in filename

### ISSUE THREAD

**Issue by ystoneman** [aws-samples/aws-genai-llm-chatbot#452]
I tried uploading a PDF with spaces in the name ("Executive Order on the Safe, Secure, and Trustworthy Development and Use of Artificial Intelligence _ The White House.pdf") using the Chatbot's UI. This failed, and the UI showed me a generic error ("Uploading files Upload failed"). Chrome's dev tools showed me it was an S3/CloudFront issue:

"Failed to load resource: the server responded with a status of 403 (Forbidden)."
<img width="1083" alt="Screenshot 2024-04-14 at 4 46 00 PM" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/20830609/fd6fc6ee-e8bb-4728-9da3-cb67a4baa899">

Replacing the spaces with underscores in the name ("Executive_order_AI.pdf") made the error go away and the file upload.

To improve UX I would either:

1. Improve the UI's error message to tell users that the filename contains invalid characters (like spaces) and tells them the filename requirements.
2. Or even better, automatically normalize the filename before upload by replacing spaces with underscores, truncating if needed, and applying other necessary transformations for S3 compatibility.

**Comment by azaylamba** [comment]
Actually, the issue is not with using spaces, the issue is with having comma(,) in the file name.

**Comment by azaylamba** [comment]
This can be closed now as the fix has been merged to main.
