### ISSUE TITLE
Error: Command failed: npm --silent --prefix "/home/ubuntu/environment/aws-genai-llm-chatbot/lib/user-interface/react-app" ci

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#453]
Dear all,
I have the following issue during the 'npx cdk deploy --verbose':

...
Bundling asset genaiGenAIChatBotStack/Shared/genai-core/57ec57/Stage...
  adding: genai_core/ (stored 0%)
  adding: genai_core/types.py (deflated 55%)
  adding: genai_core/semantic_search.py (deflated 71%)
  adding: genai_core/registry/ (stored 0%)
  adding: genai_core/registry/__init__.py (deflated 28%)
  adding: genai_core/registry/index.py (deflated 56%)
  adding: genai_core/sessions.py (deflated 73%)
  adding: genai_core/chunks.py (deflated 74%)
  adding: genai_core/embeddings.py (deflated 70%)
  adding: genai_core/clients.py (deflated 65%)
  adding: genai_core/opensearch/ (stored 0%)
  adding: genai_core/opensearch/chunks.py (deflated 71%)
  adding: genai_core/opensearch/__init__.py (deflated 38%)
  adding: genai_core/opensearch/query.py (deflated 77%)
  adding: genai_core/opensearch/delete.py (deflated 66%)
  adding: genai_core/opensearch/client.py (deflated 54%)
  adding: genai_core/opensearch/create.py (deflated 71%)
  adding: genai_core/aurora/ (stored 0%)
  adding: genai_core/aurora/chunks.py (deflated 76%)
  adding: genai_core/aurora/utils.py (deflated 53%)
  adding: genai_core/aurora/__init__.py (deflated 43%)
  adding: genai_core/aurora/query.py (deflated 81%)
  adding: genai_core/aurora/delete.py (deflated 64%)
  adding: genai_core/aurora/connection.py (deflated 64%)
  adding: genai_core/aurora/create.py (deflated 75%)
  adding: genai_core/upload.py (deflated 53%)
  adding: genai_core/models.py (deflated 79%)
  adding: genai_core/auth.py (deflated 23%)
  adding: genai_core/cross_encoder.py (deflated 65%)
  adding: genai_core/parameters.py (deflated 63%)
  adding: genai_core/langchain/ (stored 0%)
  adding: genai_core/langchain/__init__.py (deflated 13%)
  adding: genai_core/langchain/workspace_retriever.py (deflated 66%)
  adding: genai_core/langchain/chat_message_history.py (deflated 72%)
  adding: genai_core/documents.py (deflated 81%)
  adding: genai_core/user_feedback.py (deflated 56%)
  adding: genai_core/utils/ (stored 0%)
  adding: genai_core/utils/websocket.py (deflated 41%)
  adding: genai_core/utils/delete_files_with_prefix.py (deflated 65%)
  adding: genai_core/utils/files.py (deflated 47%)
  adding: genai_core/utils/comprehend.py (deflated 62%)
  adding: genai_core/utils/json.py (deflated 53%)
  adding: genai_core/kendra/ (stored 0%)
  adding: genai_core/kendra/data_sync.py (deflated 74%)
  adding: genai_core/kendra/indexes.py (deflated 67%)
  adding: genai_core/kendra/__init__.py (deflated 42%)
  adding: genai_core/kendra/query.py (deflated 68%)
  adding: genai_core/kendra/delete.py (deflated 69%)
  adding: genai_core/kendra/client.py (deflated 68%)
  adding: genai_core/websites/ (stored 0%)
  adding: genai_core/websites/crawler.py (deflated 67%)
  adding: genai_core/websites/__init__.py (stored 0%)
  adding: genai_core/websites/sitemap.py (deflated 64%)
  adding: genai_core/workspaces.py (deflated 82%)
  adding: index.py (deflated 68%)
  adding: adapters/ (stored 0%)
  adding: adapters/claude.py (deflated 67%)
  adding: adapters/base.py (deflated 49%)
  adding: adapters/idefics.py (deflated 69%)
  adding: adapters/__init__.py (deflated 26%)
  adding: content_handler.py (deflated 47%)
Bundling asset genaiGenAIChatBotStack/UserInterface/UserInterfaceDeployment/Asset1/Stage...
Error: Command failed: npm --silent --prefix "/home/ubuntu/environment/aws-genai-llm-chatbot/lib/user-interface/react-app" ci
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.tryBundle (/home/ubuntu/environment/aws-genai-llm-chatbot/lib/user-interface/index.ts:183:23)
    at AssetStaging.bundle (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:33)
    at AssetStaging.stageByBundling (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:5297)
    at stageThisAsset (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2728)
    at Cache.obtain (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/private/cache.js:1:242)
    at new AssetStaging (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:3125) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6919,
  stdout: null,
  stderr: null
}
...

best regards
Alexey Shishkin

**Comment by shahbhavik01** [comment]
Hello, I have this issue as well. Any updates would be appreciated.
