### ISSUE TITLE
current credentials could not be used to assume the role

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#454]
Dear all,

During the deployment via 'npx cdk deploy' in Cloud9 environment I get the following warning messages:

current credentials could not be used to assume 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-lookup-role-XXXXXXXXXXXX-YYYYYYYYY', but are for the right account. Proceeding anyway.
current credentials could not be used to assume 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-deploy-role-XXXXXXXXXXXX-YYYYYYYYY', but are for the right account. Proceeding anyway.
current credentials could not be used to assume 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-file-publishing-role-XXXXXXXXXXXX-YYYYYYYYY', but are for the right account. Proceeding anyway.
current credentials could not be used to assume 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-image-publishing-role-XXXXXXXXXXXX-YYYYYYYYY', but are for the right account. Proceeding anyway.

and the deployment rolls back.

I have admin permissions and the roles mentioned above exist.

How can I fix this issue ?

best regards
Alexey Shishkin

**Comment by alexeyshishkin01** [comment]
it looks like the issue was with the restrictions for temporary managed credentials in Cloud9, so I had to switch to SSO

am I alone who hit this issue ?

**Comment by yota-p** [comment]
faced same issue on Cloud9. switching to different AWS credentials worked for me
