### ISSUE TITLE
Feature Request: Private Workspaces

### ISSUE THREAD

**Issue by vipetrul** [aws-samples/aws-genai-llm-chatbot#455]
Implement the ability for users to create private workspaces they own and control access to. Key requirements:

1. Workspaces owned by creating user.
2. Owner can grant read-only or read/write access to other users.
3. No administrator role required for workspace/permission management.

**Rationale:**
This feature has been requested before but never implemented. Allowing users to have private workspaces they control access to would be a valuable capability.

**Technical Considerations:**
Some re-modeling of DynamoDB tables may be required to efficiently handle data retrieval for private workspaces and access controls.

If the team thinks this feature would be of value, I could help with the implementation.

**Comment by hghandri** [comment]
Hi,

there is a PR already opened about this subject, perhaps we could improve this one to accelerate adoption ?

++
