### ISSUE TITLE
Typo? Should this be 'npm run create'?

### ISSUE THREAD

**Issue by steditt** [aws-samples/aws-genai-llm-chatbot#469]
I think this is a typo. The command should be 'npm run create'.

https://github.com/aws-samples/aws-genai-llm-chatbot/blob/6a40028fc4602d84bc0e91973dbac050ba8cb3f1/docs/guide/deploy.md?plain=1#L107

**Comment by Rob-Powell** [comment]
No it used to be 'npm run create' but it was updated to now be 'npm run config'
