### ISSUE TITLE
Installer does not prompt for Secrets Manager Secret ARN containing HF API token

### ISSUE THREAD

**Issue by sergio0137** [aws-samples/aws-genai-llm-chatbot#470]
According to the project documentation, enabling SageMaker models in the installer should prompt the user for a Secrets Manager Secret ARN containing the Hugging Face API token. However, this prompt is not occurring.

I have reviewed the project documentation and verified that enabling SageMaker models should trigger the prompt for the Secrets Manager Secret ARN.

There are no error messages or logs indicating any issues during the installation process.

I have tried running the installer multiple times with different configurations, but the prompt for the Secrets Manager Secret ARN never appears.

Thank you for your attention !

**Comment by Rob-Powell** [comment]
did you update the project to the latest version of code? this is a new feature.
i.e `git fetch && git pull`

**Comment by sergio0137** [comment]
Right, I have seen that those changes are from 4 days ago. Updating the code has fixed the issue.

Thank you very much for the support.

I take this opportunity to tell you that the project is amazing, congratulations.
