### ISSUE TITLE
Condition disappear for Idefics activation

### ISSUE THREAD

**Issue by hghandri** [aws-samples/aws-genai-llm-chatbot#477]
Hi,

since release version 4.0.3 it seems there is condition disappeared for Idefics Interface activation or not.

You can compare this latest version with previous one like v4.0.3 at the same line : 

https://github.com/aws-samples/aws-genai-llm-chatbot/blob/3c710bf28bd74eb3b576b863a4b678ed8ef06e0b/lib/aws-genai-llm-chatbot-stack.ts#L110

is it normal or a mistake ? In my case I cannot not deploy anymore due this new resource not available before and it need a default security group ID for private VPC endpoint.
This happened when VPC already exist, it seems the method "ec2.Vpc.fromLookup" does not detect a default security group.

Here the impact : 

https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/model-interfaces/idefics/index.ts#L41

This property "props.shared.vpc.vpcDefaultSecurityGroup" should contains a default security group ID.
For an existing VPC this value seems to be blank.

This condition impact also ResourcePath for NagSuppressions.

Best regards,

**Comment by hghandri** [comment]
Hi,

anyone could check this issue ?

**Comment by KietNgoTuan** [comment]
Hello
@hghandri i had the same error when using the existing VPC with  Idefics Interface can not find the default security group ID.
Do you find the solution about this problem ?

**Comment by hghandri** [comment]
I've just opened a PR : #498
