### ISSUE TITLE
VPCEndpoint trying to create even if "createVpcEndpoints": false

### ISSUE THREAD

**Issue by BryceViva** [aws-samples/aws-genai-llm-chatbot#482]
I have the config set to be privatewebsite = true and "createVpcEndpoints": false, but when I run CDK Deploy, It still tries to deploy a VPCEndpoint. I am unable to deploy endpoints in the environment this is going.

Am I missing some flag to make sure an Endpoint isn't going to be created?

Thanks for all help.

**Comment by kmanuwai** [comment]
The definition of a private website here is that the website will only be accessible from the VPC or any client (i.e. on a VPN) that can reach the internal only Application Load Balancer that sits in front of the S3 hosted website.

So you need VPC Endpoints to be deployed for that to work. I.e. privatewebsite = true will overpower "createVpcEndpoints": false

See here for more details: https://aws-samples.github.io/aws-genai-llm-chatbot/documentation/private-chatbot.html

**Comment by BryceViva** [comment]
Is it possible to use an existing VPC endpoint?

**Comment by kmanuwai** [comment]
You should be able to use existing VPC endpoints although I have not tested this. 
If you remove the endpoints you don't want created from here: https://github.com/aws-samples/aws-genai-llm-chatbot/blob/372710ae19ec7f8331f3190590185db711094b73/lib/shared/index.ts#L80-L82

Then in this part of the code, your already existing VPC endpoint should be picked up: https://github.com/aws-samples/aws-genai-llm-chatbot/blob/372710ae19ec7f8331f3190590185db711094b73/lib/user-interface/private-website.ts#L42

**Comment by BryceViva** [comment]
After removing the lines in the index.ts, do I need to provide the endpoint ID in the private-website.ts or is it going to auto pickup?

Thanks for the help

**Comment by kmanuwai** [comment]
I believe the VPC endpoints should be used. If not some VPC network configurations may need to be updated. Check the pre-req's here: https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html#prerequisites-interface-endpoints
