### ISSUE TITLE
CREATE_FAILED during npx cdk deploy

### ISSUE THREAD

**Issue by GiuseppeSergi3** [aws-samples/aws-genai-llm-chatbot#483]
Hello everyone, after running the 'npx cdk deploy' command, I'm encountering the following errors that lead to deployment failure:
![errore](https://github.com/aws-samples/aws-genai-llm-chatbot/assets/100352697/2d166ea4-c4e4-46b6-bd85-4221c63df6fd)

I'm trying to deploy the chatbot (via Cloud9 environment) in the Paris region.
Does anyone know how to resolve this?

Thank you,
Giuseppe

**Comment by kzaini** [comment]
Same thing is happening to me. Any ideas on how to solve?

**Comment by Rob-Powell** [comment]
What region are you deploying to? I suspect different regions with different instance types available and M6A isnt available in your region.

 the code where that is set is here:
https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/rag-engines/data-import/file-import-batch-job.ts#L41 
https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/rag-engines/data-import/web-crawler-batch-job.ts#L41

you can see instance types by region here:
https://docs.aws.amazon.com/ec2/latest/instancetypes/ec2-instance-regions.html

Pick a different one thats available in your region and then build and deploy the changes again.

**Comment by GiuseppeSergi3** [comment]
I'm deploying in Paris. I've noticed that indeed M6A isn't available, but I need to deploy in this region to use the multimodal models. Is there a solution?

**Comment by Rob-Powell** [comment]
yep,
Ok looks like paris supports `m5a` as a workaround modify those files i mentioned:

https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/rag-engines/data-import/file-import-batch-job.ts#L41
https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/rag-engines/data-import/web-crawler-batch-job.ts#L41

replace M6A with M5A and try another deployment after running `npm run build` then deploy as normal with `npx cdk deploy`
