### ISSUE TITLE
CREATE_FAILED due to this error "The request must contain the parameter groupName or groupId"

### ISSUE THREAD

**Issue by KietNgoTuan** [aws-samples/aws-genai-llm-chatbot#493]
Hello 
I'm trying to deploy the Genai chatbot with existing VPC. But i received this error while running "npx cdk deploy"

`
10:24:47 AM | CREATE_FAILED        | AWS::EC2::SecurityGroupIngress            | IdeficsInterfaceVP...03700164437BF22E71
Resource handler returned message: "The request must contain the parameter groupName or groupId (Service: Ec2, Status Code: 400, Request ID: 81e23880-5afb-4181-b5e6-0872a7462303)" (RequestToken: abad1921
-95ee-3f14-c65c-89764b402f19, HandlerErrorCode: InvalidRequest)

10:24:49 AM | CREATE_FAILED        | AWS::SQS::QueuePolicy                     | ChatBotApiRealtime...sDLQPolicy709D8CBC
Internal Failure

10:24:49 AM | CREATE_FAILED        | AWS::SQS::Queue                           | ChatBotApiRealtime...sagesQueue92DD6F2A
❌  devopsGenAIChatBotStack failed: Error: The stack named devopsGenAIChatBotStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The request must contain the parameter groupName or groupId (Service: Ec2, Status Code: 400, Request ID: 99f813cf-564b-4abe-8a45-cca29b2add24)" (RequestToken: 53392423-87bb-018e-9cbc-746a3d4f9e57, HandlerErrorCode: InvalidRequest), Internal Failure, Internal Failure, Internal Failure, Internal Failure, Internal Failure, Internal Failure
    at FullCloudFormationDeployment.monitorDeployment (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk/lib/index.js:428:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk/lib/index.js:431:196745)
    at async /home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk/lib/index.js:431:178714

 ❌ Deployment failed: Error: The stack named devopsGenAIChatBotStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The request must contain the parameter groupName or groupId (Service: Ec2, Status Code: 400, Request ID: 99f813cf-564b-4abe-8a45-cca29b2add24)" (RequestToken: 53392423-87bb-018e-9cbc-746a3d4f9e57, HandlerErrorCode: InvalidRequest), Internal Failure, Internal Failure, Internal Failure, Internal Failure, Internal Failure, Internal Failure
    at FullCloudFormationDeployment.monitorDeployment (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk/lib/index.js:428:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk/lib/index.js:431:196745)
    at async /home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk/lib/index.js:431:178714` 

This error came from the Idefics Interface and i looked into the code and it seem that "ec2.Vpc.fromLookup function didn't return the correct format of VPC"
I looked into the CloudFormation template and the "Idefics Interface Endpoint" doesn't have the groupid parameter 

`"IdeficsInterfaceVPCDefaultSecurityGroupfrom103700164437BF22E71": {
   "Type": "AWS::EC2::SecurityGroupIngress",
   "Properties": {
    "CidrIp": "10.37.0.0/16",
    "Description": "from 10.37.0.0/16:443",
    "FromPort": 443,
    "IpProtocol": "tcp",
    "ToPort": 443
  `
My custom VPC is in Paris region (eu-west-3) , it has 3 subnets (1 public, 1 private and 1 isolated) in each 3 AZ 

**Can you help me about this problem please ?**
Thank you in advance

**Comment by BryceViva** [comment]
Did you happen to find a solution to this? I am running into the same thing.

**Comment by KietNgoTuan** [comment]
I'm sorry but no i don't find any solution for this

**Comment by zxkane** [comment]
Same error when deploying it into existing VPC. Could someone from the team to have a look at it?
