### ISSUE TITLE
error at processing after upload data in workspace

### ISSUE THREAD

**Issue by nasirtrekker** [aws-samples/aws-genai-llm-chatbot#500]
status Processing.... for a long time and then error .
Embeddings provider bedrock
Embeddings model amazon.titan-embed-text-v1
Embeddings dimensions 1536
engine amazon opensearch

**Comment by charles-marion** [comment]
Is it still happening? 
This integration test is verifying a similar case and is passing
https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/integtests/chatbot-api/opensearch_workspace_test.py#L55
