### ISSUE TITLE
feat(monitoring): emit cloudwatch metrics, provide cloudwatch dashboard

### ISSUE THREAD

**Issue by bigadsoleiman** [aws-samples/aws-genai-llm-chatbot#502]
An initial monitoring implementation could include metrics emitted for:
- n. of users
- n. of messages
- n. of tokens consumed (where provided by model interfaces)
- model used

and create a V1 of monitoring dashboard to display and analyse above metrics

**Comment by charles-marion** [comment]
Change is complete.
