### ISSUE TITLE
Model page does NOT represent/sync the available model from Bedrock 

### ISSUE THREAD

**Issue by nasirtrekker** [aws-samples/aws-genai-llm-chatbot#504]
This the screenshot from the webapp available models
<img width="788" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/7610299/66dbeff2-9a9e-4d4c-af5a-bc4697bacc5b">

This is the screenshot from AWS Bedrock
<img width="1164" alt="image" src="https://github.com/aws-samples/aws-genai-llm-chatbot/assets/7610299/8f50632e-aedb-45fe-889e-a55537789d07">
"amazon.titan-embed-text-v1" although this is visible inside the workspace but not visible in the model page

**Comment by Rob-Powell** [comment]
yes that's because its a model for embeddings not general chat/instruct

**Comment by nasirtrekker** [comment]
> yes that's because its a model for embeddings not general chat/instruct

also for general chat/instruct the model which was available in the Bedrock region doesnt match exactly what was showed in the chat UI :-). I thought the models which were available in the certain region will match exactactly with UI. Will redeploy with the new version and see if that still the case. Thanks .

**Comment by eldimi** [comment]
> > yes that's because its a model for embeddings not general chat/instruct
> 
> also for general chat/instruct the model which was available in the Bedrock region doesnt match exactly what was showed in the chat UI :-). I thought the models which were available in the certain region will match exactactly with UI. Will redeploy with the new version and see if that still the case. Thanks .

Do you refer to models that are not granted access but are still visible in the chat UI? This is because there is no sdk currently available to list only the enabled ones. You will get notified if you use them in the playground.
