### ISSUE TITLE
Fix Bedrock Anthropic Integration

### ISSUE THREAD

**Issue by FabioChiodini** [aws-samples/aws-genai-llm-chatbot#52]
Given that the invocation of Anthropic has changed in Bedrock could you please fix it to make it work again?

"We are requiring all Amazon Bedrock customers consuming Anthropic’s Claude to send prompts to the model in the following syntax: “\n\nHuman: <Customer Prompt>\n\nAssistant:”."

Now the invocation of Claude fails with this error:

"<class 'ValueError'>:Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: Invalid prompt: prompt must end with "

Assistant:" turn"

Thank you very much.

**Comment by massi-ang** [comment]
This is addresses by #55
