### ISSUE TITLE
Models dropdown shows `azure:openai`even if no models have been configured

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/aws-genai-llm-chatbot#543]
I have pulled the latest commit and re-deployed the chatbot on an existing installation. 
Now I am getting

<img width="463" alt="image" src="https://github.com/user-attachments/assets/4c292a4a-4ecb-44db-a091-5bfa0525a68c">

at the top of my models list.

**Comment by grinko** [comment]
Fixed 
<img width="533" alt="Screenshot 2024-08-14 at 11 13 49 AM" src="https://github.com/user-attachments/assets/464daf10-807e-4576-b1c5-b885f382e6c7">
