### ISSUE TITLE
Add Bedrock Cohere Command Text model 

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/aws-genai-llm-chatbot#58]
Add support for Bedrock Cohere Command Text model

**Comment by massi-ang** [comment]
This fix add the Bedrock adapter for Cohere models but needs support from Langchain to work.
Depends on https://github.com/langchain-ai/langchain/pull/11230

**Comment by bigadsoleiman** [comment]
- https://github.com/langchain-ai/langchain/pull/11230 released
- #83 merged
