### ISSUE TITLE
Deployment fails in eu-west-3 region because of invalid scope for waf v2

### ISSUE THREAD

**Issue by sebbri-aws** [aws-samples/aws-genai-llm-chatbot#585]
I deploy in the eu-west-3 (Paris) region.
 
The deployment fails during the cloudformation GenAIChatBotStack creation with the following error :

8:23:22 AM | CREATE_FAILED        | AWS::WAFv2::WebACL                              | UserInterfacePubli...CloudfrontDA13790E

The CloudFormation associated event is : Resource handler returned message: "Error reason: The scope is not valid., field: SCOPE_VALUE, parameter: CLOUDFRONT (Service: Wafv2, Status Code: 400, Request ID: 454ca0f2-09c2-4243-bcf6-cd4df5fcdc3b)" (RequestToken: db081d6c-3186-7c2d-f7f5-118806083094, HandlerErrorCode: InvalidRequest)

I already did a previous installation in the same account but in another region. There may be a relationship with this error.

**Comment by charles-marion** [comment]
Apologies. I reverting the cause that was causing this issue.

Thank you for reporting it!

**Comment by sebbri-aws** [comment]
Thank you.
I retry and will come back to you if necessary.

**Comment by sebbri-aws** [comment]
It works. The issue is solved.
Thank you.
