### ISSUE TITLE
Creation of a workspace fails

### ISSUE THREAD

**Issue by sebbri-aws** [aws-samples/aws-genai-llm-chatbot#590]
I installed the commit[77ec531]([77ec531](https://github.com/aws-samples/aws-genai-llm-chatbot/commit/77ec531e13100519e3dd0582be1c612aedee9524)) in the region of Paris (eu-west-3).

The creation of a workspace fails with the message : 'Something went wrong'.

**Comment by sebbri-aws** [comment]
I also found the following entry in cloudwatch :
{
    "logType": "RequestMapping",
    "path": [
        "createAuroraWorkspace"
    ],
    "fieldName": "createAuroraWorkspace",
    "resolverArn": "arn:aws:appsync:eu-west-3:697705234509:apis/taq4muotnzbklktokvyt6hrxuq/types/Mutation/resolvers/createAuroraWorkspace",
    "requestId": "d0d6e101-4652-4c48-9178-7593a5bcad39",
    "context": {
        "arguments": {
            "input": {
                "name": "ws1",
                "kind": "aurora",
                "embeddingsModelProvider": "bedrock",
                "embeddingsModelName": "amazon.titan-embed-text-v1",
                "crossEncoderModelProvider": "sagemaker",
                "crossEncoderModelName": "cross-encoder/ms-marco-MiniLM-L-12-v2",
                "languages": [
                    "english",
                    "french"
                ],
                "metric": "inner",
                "index": true,
                "hybridSearch": true,
                "chunkingStrategy": "recursive",
                "chunkSize": 1000,
                "chunkOverlap": 200
            }
        },
        "stash": {},
        "outErrors": []
    },
    "fieldInError": false,
    "errors": [],
    "parentType": "Mutation",
    "graphQLAPIId": "taq4muotnzbklktokvyt6hrxuq"
}

**Comment by sebbri-aws** [comment]
`{
    "logType": "ResponseMapping",
    "path": [
        "createAuroraWorkspace"
    ],
    "fieldName": "createAuroraWorkspace",
    "resolverArn": "arn:aws:appsync:eu-west-3:697705234509:apis/taq4muotnzbklktokvyt6hrxuq/types/Mutation/resolvers/createAuroraWorkspace",
    "requestId": "d0d6e101-4652-4c48-9178-7593a5bcad39",
    "context": {
        "arguments": {
            "input": {
                "name": "ws1",
                "kind": "aurora",
                "embeddingsModelProvider": "bedrock",
                "embeddingsModelName": "amazon.titan-embed-text-v1",
                "crossEncoderModelProvider": "sagemaker",
                "crossEncoderModelName": "cross-encoder/ms-marco-MiniLM-L-12-v2",
                "languages": [
                    "english",
                    "french"
                ],
                "metric": "inner",
                "index": true,
                "hybridSearch": true,
                "chunkingStrategy": "recursive",
                "chunkSize": 1000,
                "chunkOverlap": 200
            }
        },
        "stash": {},
        "error": {
            "message": "Something went wrong",
            "type": "RuntimeError",
            "unhandledErrorType": "RuntimeError"
        },
        "outErrors": []
    },
    "fieldInError": true,
    "errors": [
        "CustomTemplateException(message=Something went wrong, errorType=RuntimeError, data=null, errorInfo=null)"
    ],
    "parentType": "Mutation",
    "graphQLAPIId": "taq4muotnzbklktokvyt6hrxuq"
}`

**Comment by charles-marion** [comment]
@sebbri-aws , thank you for the update.

For future reference, the log above is the Appsync log I believe. To view the error you would need to check the lambda log that is resolving the request (Log group for this lambda is in the CloudWatch Dasboard)
