### ISSUE TITLE
Error with OpenSearch Name Length

### ISSUE THREAD

**Issue by QuinnGT** [aws-samples/aws-genai-llm-chatbot#70]
Not sure if others have seen this error but tried deploying the OpenSearch RAG and got this error.

`Properties validation failed for resource RagEnginesOpenSearchVectorAccessPolicyrestapi7C36C959 with message:
#/Name: failed validation constraint for keyword [pattern]`

Reading around it looks like it may be case or max character related. Not sure, still testing.

**Comment by QuinnGT** [comment]
Realized I didn't put the resource it failed on.

``DevGenAIChatBotStack |  74/262 | 8:34:45 AM | CREATE_FAILED        | AWS::IAM::Role                                  | Custom::VpcRestrictDefaultSGCustomResourceProvider/Role (CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0) Resource creation cancelled``

**Comment by QuinnGT** [comment]
Update. First run I tried to add the OpenSearch RAG to my existing build and it failed on the access policy. 2nd run today I did fresh and it failed on the VPC endpoint.

`DevGenAIChatBotStack |  69/262 | 8:34:45 AM | CREATE_FAILED        | AWS::OpenSearchServerless::VpcEndpoint          | RagEngines/OpenSearchVector/VpcEndpoint (RagEnginesOpenSearchVectorVpcEndpoint0433102C) Properties validation failed for resource RagEnginesOpenSearchVectorVpcEndpoint0433102C with message:
#/Name: failed validation constraint for keyword [pattern]`

**Comment by spugachev** [comment]
Pull request has been accepted
