### ISSUE TITLE
Kendra not syncing data source

### ISSUE THREAD

**Issue by QuinnGT** [aws-samples/aws-genai-llm-chatbot#74]
**Steps to recreate:**
1. Create a new workspace on Kendra with your index created during deployment 
2. Upload documents and wait for documents to show processed
3. Run query on documents, no results will show in metadata 
4. Go to Kendra index > Data Sources in AWS console 
5. Data source sync history will show empty and no last run time

**Things to note:**
1. Kendra processed status is almost instant in workspace view but typically it takes a few minutes, depending on the document size. 
2. v2 of the Kendra Rag would start the sync after you uploaded documents. Might be worth comparing v3 to v2.

**Comment by spugachev** [comment]
Yes, updating the Kendra index takes more time. Pressing the "Start Kendra Data Sync" button is required. After doing so, it takes a few minutes to sync the Kendra Index. We no longer sync it after each file upload. 

I agree that a clearer status indication is necessary.
