### ISSUE TITLE
Get the source document(s) link when using RAG

### ISSUE THREAD

**Issue by vincentcabosart** [aws-samples/aws-genai-llm-chatbot#84]
Get the source document(s) reference when using Amazon Kendra RAG. This would be easier for users to know from which document(s) the answer comes from. And they could then read further the right document(s).

**Comment by superuser5** [comment]
I can see this data in the metadata. Got to settings on the bottom right and enable metadata. The fields title and path will be there.

**Comment by kmanuwai** [comment]
A clickable link to the document would be extremely useful. Even better a link that leads directly to the relevant chunk within the document.

**Comment by azaylamba** [comment]
This feature would be very helpful for the users.

**Comment by azaylamba** [comment]
For the file based documents, we can provide a link to download the file from S3.
