### ISSUE TITLE
The models.py script referenced in readme.md (step 3) doesn't exist.

### ISSUE THREAD

**Issue by jawhnycooke** [aws-samples/aws-genai-llm-chatbot#85]
https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/model-interfaces/langchain/README.md

The models.py script referenced in readme.md step 3 used for creating adaptors for other FMs doesn't exist.

**Comment by bigadsoleiman** [comment]
Thanks for reporting this.

Fixed the [README](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/model-interfaces/langchain/README.md) according to new version
