### ISSUE TITLE
Conversation history issue

### ISSUE THREAD

**Issue by l-guida** [aws-samples/aws-genai-llm-chatbot#92]
Just wanted to report an unexpected behaviour, most probably caused by the LangChain conversation history feature used behind the scenes of this solution.

- Asking the same question against the same workspace in different moments of the conversations sometimes brings strikingly different results. For example, if I ask a specific question at the beginning of a conversation, I get a clear and comprehensive answer; if I ask the same question after a few interactions with the agent, sometimes I get no answer at all (e.g., "I don’t know", "I can’t find this information", …), or the answer to a question asked previously.

**Comment by bigadsoleiman** [comment]
Fixed in [#154](https://github.com/aws-samples/aws-genai-llm-chatbot/issues/154)
