### ISSUE TITLE
RAG stops working after first successful query

### ISSUE THREAD

**Issue by samuelbaruffi** [aws-samples/aws-genai-llm-chatbot#93]
When using the RAG system in the chatbot, I noticed an issue where the first query works as expected but subsequent identical queries do not return any results from the vector store. 

For example:

1. Ask "Who introduced ratings to the US?" 
- Returns a vector with score > 0 and relevant text snippet

2. Ask the exact same question again
- No vector returned, even though it was previously found

It seems like the context is not being maintained properly between queries in Langchain. The initial RAG query saves the vector/text to the context, but that context is not reused on follow-up identical questions.

This defeats the purpose of the RAG system, since the user would expect to get the same semantic search results when asking the same question multiple times.

Ideally the chatbot should return the same text snippet even on repeated queries, as long as the original vector is still available in the index.

Let me know if any other info would be helpful in debugging this further. Thanks!

**Comment by QuinnGT** [comment]
Confirmed it only does this with OpenSearch and Aurora RAGs. Kendra works past the first query.
